import test from'node:test';import assert from'node:assert/strict';import{worldEventText,mandatorySummary,recoverySummary,statusSummary}from'../dist/display-contract.js';

test('world event uses authoritative public snapshot with safe null fallback',()=>{assert.equal(worldEventText({game:{eventName:'Drought'}}),'Drought');assert.equal(worldEventText({game:{eventName:null}}),'Không có');assert.equal(worldEventText(null),'Không có')});

test('mandatory summary preserves authoritative projected liquidation and bankruptcy facts',()=>{const q={breakdown:{living:10,socialContribution:2,tax:3,childSupport:4,parentSupport:5,grief:6,medical:7,total:37},netIncome:8,cashBefore:9,liquidationRequired:true,liquidationProceeds:20,cashAfterLiquidation:29,projectedBankruptcy:true,shortfall:8,dominantCost:'living'};assert.deepEqual(mandatorySummary(q),{total:37,cashBefore:9,liquidationRequired:true,liquidationProceeds:20,cashAfterLiquidation:29,projectedBankruptcy:true,shortfall:8,dominantCost:'Sinh hoạt'})});

test('recovery summary renders server quote without recomputing cost or capacity',()=>{assert.equal(recoverySummary({grade:'mid',currentPool:12,carryingCapacity:30,pendingNextRound:4,capacityRemaining:14,costPerUnit:7.5}),'MID · Pool 12/30 · Pending +4 · Còn 14 · 7,5/đơn vị')});

test('status summary preserves fees, persons charged, affordability and noble fallback facts',()=>{const q={roundAverageAssets:100,priceIndex:1.2,cards:[{status:'poor',fee:10,personsCharged:2,affordable:true},{status:'middle',fee:20,personsCharged:2,affordable:true},{status:'noble',fee:40,personsCharged:2,affordable:false}],nobleCompetition:{slotsTotal:3,slotsRequired:2,pendingNobleSlots:1,incumbent:false,householdAssets:120,turnCard:9,priority:['incumbent','householdAssets','turnCard'],allocationTiming:'end_of_round',fallbackStatus:'middle',middleFallbackFee:20,potentialRefund:20}};const s=statusSummary(q);assert.equal(s.cards[2].fee,40);assert.equal(s.cards[2].affordable,false);assert.equal(s.noble.middleFallbackFee,20);assert.equal(s.noble.potentialRefund,20)});
