import test from'node:test';import assert from'node:assert/strict';import{readFileSync}from'node:fs';import{worldEventText,mandatorySummary,recoverySummary,statusSummary,rememberSnapshot,currentSnapshot}from'../dist/display-contract.js';
const source=readFileSync(new URL('../src/display-contract.ts',import.meta.url),'utf8');

test('world event uses authoritative public snapshot with safe null fallback',()=>{assert.equal(worldEventText({game:{eventName:'Drought'}}),'Drought');assert.equal(worldEventText({game:{eventName:null}}),'Không có');assert.equal(worldEventText(null),'Không có')});

test('mandatory summary preserves authoritative projected liquidation and bankruptcy facts',()=>{const q={breakdown:{living:10,socialContribution:2,tax:3,childSupport:4,parentSupport:5,grief:6,medical:7,total:37},netIncome:8,cashBefore:9,liquidationRequired:true,liquidationProceeds:20,cashAfterLiquidation:29,projectedBankruptcy:true,shortfall:8,dominantCost:'living'};assert.deepEqual(mandatorySummary(q),{total:37,cashBefore:9,liquidationRequired:true,liquidationProceeds:20,cashAfterLiquidation:29,projectedBankruptcy:true,shortfall:8,dominantCost:'Sinh hoạt'})});

test('recovery summary renders server quote without recomputing cost or capacity',()=>{assert.equal(recoverySummary({grade:'mid',currentPool:12,carryingCapacity:30,pendingNextRound:4,capacityRemaining:14,costPerUnit:7.5}),'MID · Pool 12/30 · Pending +4 · Còn 14 · 7,5/đơn vị')});

test('status summary preserves fees, persons charged, affordability and noble fallback facts',()=>{const q={roundAverageAssets:100,priceIndex:1.2,cards:[{status:'poor',fee:10,personsCharged:2,affordable:true},{status:'middle',fee:20,personsCharged:2,affordable:true},{status:'noble',fee:40,personsCharged:2,affordable:false}],nobleCompetition:{slotsTotal:3,slotsRequired:2,pendingNobleSlots:1,incumbent:false,householdAssets:120,turnCard:9,priority:['incumbent','householdAssets','turnCard'],allocationTiming:'end_of_round',fallbackStatus:'middle',middleFallbackFee:20,potentialRefund:20}};const s=statusSummary(q);assert.equal(s.cards[2].fee,40);assert.equal(s.cards[2].affordable,false);assert.equal(s.noble.middleFallbackFee,20);assert.equal(s.noble.potentialRefund,20)});

test('latest authoritative snapshot survives local UI render without a new network snapshot',()=>{const recoveryQuotes=[{grade:'low',currentPool:1,carryingCapacity:10,pendingNextRound:2,capacityRemaining:7,costPerUnit:3},{grade:'mid',currentPool:4,carryingCapacity:20,pendingNextRound:5,capacityRemaining:11,costPerUnit:6},{grade:'high',currentPool:7,carryingCapacity:30,pendingNextRound:8,capacityRemaining:15,costPerUnit:9}];const detail={room:{game:{eventName:'Storm'}},player:{recoveryQuotes}};rememberSnapshot(detail);assert.equal(currentSnapshot(),detail);assert.equal(currentSnapshot().player.recoveryQuotes.length,3);assert.equal(recoverySummary(currentSnapshot().player.recoveryQuotes[2]),'HIGH · Pool 7/30 · Pending +8 · Còn 15 · 9/đơn vị')});

test('local data-panel clicks schedule redecorate from cached authoritative snapshot',()=>{assert.ok(source.includes('latestSnapshot'));assert.ok(source.includes('target?.closest?.("[data-panel]")'));assert.ok(source.includes('window.setTimeout(redecorateLatest,0)'));assert.ok(source.includes('renderRecovery(detail.player)'));assert.ok(source.includes('renderMandatory(detail.player)'));assert.ok(source.includes('renderStatus(detail.player)'));assert.ok(source.includes('renderEvent(detail.room)'))});
