import type{PlayerSnapshot,RoomSnapshot}from"./types.js";
type Detail={room:RoomSnapshot|null;player:PlayerSnapshot|null};
let latest:Detail={room:null,player:null},scheduled=false;
const vi=(x:any)=>Number.isFinite(Number(x))?Number(x).toLocaleString("vi-VN"):"—";
const esc=(x:any)=>String(x??"").replace(/[&<>\"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[c]!));
const label=(x:string)=>x==="noble"?"Quý tộc":x==="middle"?"Trung lưu":"Bình dân";
function schedule(){if(scheduled)return;scheduled=true;queueMicrotask(()=>{scheduled=false;decorate()})}
function toast(text:string){let x=document.querySelector<HTMLElement>(".approved-toast");if(!x){x=document.createElement("div");x.className="approved-toast";document.body.appendChild(x)}x.textContent=text;x.hidden=false;window.setTimeout(()=>{if(x)x.hidden=true},2200)}
function statusCards(){const root=document.querySelector<HTMLElement>(".status-card"),q=latest.player?.statusQuote;if(!root||!q)return;const cards=[...root.querySelectorAll<HTMLButtonElement>(".status-grid > button")];for(let i=0;i<cards.length;i++){const card=cards[i]!,quote=q.cards[i];if(!quote||card.dataset.quoteSig===`${quote.fee}:${quote.affordable}:${quote.personsCharged}`)continue;card.dataset.quoteSig=`${quote.fee}:${quote.affordable}:${quote.personsCharged}`;card.querySelector(".approved-status-quote")?.remove();const box=document.createElement("span");box.className="approved-status-quote";box.innerHTML=`<b>Phí ${vi(quote.fee)}</b><small>${quote.personsCharged>1?`Hộ ${quote.personsCharged} người · `:""}${quote.affordable?"ĐỦ KHẢ NĂNG CHI TRẢ":"KHÔNG ĐỦ CASH"}</small><em>HIỆU LỰC VÒNG SAU</em>`;card.appendChild(box);if(!quote.affordable){card.disabled=true;card.title="Không đủ cash theo quote authoritative hiện tại."}}
 const noble=cards[2];if(noble&&!noble.querySelector(".noble-wait-note")){const n=document.createElement("small");n.className="noble-wait-note";n.textContent="Nếu chọn: ĐANG CHỜ XẾP HẠNG CUỐI VÒNG · Noble chưa được đảm bảo.";noble.appendChild(n)}}
function hudTrends(){const g=latest.room?.game,root=document.querySelector<HTMLElement>(".approved-hud");if(!g||!root)return;const hs=g.historySnapshots||[];if(hs.length<2)return;const a=hs[hs.length-2],b=hs[hs.length-1];const rows=[{name:"DÂN SỐ",before:Number(a.population),after:Number(b.population)},{name:"LẠM PHÁT",before:Number(a.inflationRate),after:Number(b.inflationRate)}];for(const row of rows){const span=[...root.querySelectorAll<HTMLElement>("span")].find(x=>x.querySelector("small")?.textContent?.trim()===row.name);if(!span)continue;let trend=span.querySelector<HTMLElement>(".approved-trend");if(!trend){trend=document.createElement("em");trend.className="approved-trend";span.appendChild(trend)}const d=row.after-row.before;trend.textContent=d>0?` ↑ +${row.name==="LẠM PHÁT"?(d*100).toFixed(1)+"đ%":vi(d)}`:d<0?` ↓ ${row.name==="LẠM PHÁT"?(d*100).toFixed(1)+"đ%":vi(d)}`:" → 0";trend.title=`Thay đổi authoritative từ snapshot vòng trước: ${trend.textContent}`}}
function takeoverNotice(){const r=latest.room;if(!r)return;for(const p of r.players){if(!p.aiTakeoverCharacterId)continue;const key=`ic:takeover-seen:${p.aiTakeoverCharacterId}`;if(sessionStorage.getItem(key))continue;sessionStorage.setItem(key,"1");const name=p.displayName||"Người chơi";toast(`NHÂN VẬT ${name} HIỆN DO NPC ĐIỀU KHIỂN`)}}
function birthStates(){const root=document.querySelector<HTMLElement>('.feature-sheet[data-tutorial-zone="birth"]'),g=latest.room?.game,p=latest.player,cid=p?.character?.id;if(!root||!g||!p||!cid)return;const mine=(g.birthProposals||[]).filter((x:any)=>x.proposerCharacterId===cid);let deck=root.querySelector<HTMLElement>(".approved-birth-outgoing");if(!mine.length){deck?.remove();return}const sig=mine.map((x:any)=>`${x.id}:${x.status}:${x.index}`).join("|");if(deck?.dataset.sig===sig)return;if(!deck){deck=document.createElement("section");deck.className="approved-birth-outgoing";root.appendChild(deck)}deck.dataset.sig=sig;deck.innerHTML=`<h3>ĐỀ XUẤT CỦA BẠN</h3>${mine.map((x:any)=>`<article><b>CON #${esc(x.index||"—")}</b><span>${esc(String(x.status||"pending").toUpperCase())}</span><small>Thực hiện cuối vòng chỉ khi server giữ proposal ở trạng thái hợp lệ.</small></article>`).join("")}`}
function postgameChronicle(){const root=document.querySelector<HTMLElement>(".approved-end-card"),p=latest.player,g=latest.room?.game;if(!root||!p||!g)return;let nav=root.querySelector<HTMLElement>(".end-actions");if(!nav||nav.querySelector("[data-postgame-chronicle]"))return;const b=document.createElement("button");b.dataset.postgameChronicle="1";b.textContent="XEM NIÊN SỬ";nav.prepend(b);const panel=document.createElement("section");panel.className="postgame-chronicle";panel.hidden=true;panel.innerHTML=`<h2>NIÊN SỬ · CHỈ ĐỌC</h2><h3>HÀNH TRÌNH</h3>${(p.history?.events||[]).slice().reverse().map((x:any)=>`<p><b>Vòng ${vi(x.round)} · Năm ${vi(x.year)}</b> ${esc(x.detail)}</p>`).join("")||"<p>Chưa có lịch sử cá nhân.</p>"}<h3>THẾ GIỚI</h3>${(g.historySnapshots||[]).slice(-12).reverse().map((x:any)=>`<p><b>Vòng ${vi(x.round)}</b> · Dân số ${vi(x.population)} · Nợ ${vi(x.publicDebt)}${x.eventName?` · ${esc(x.eventName)}`:""}</p>`).join("")}`;root.appendChild(panel);b.onclick=()=>{panel.hidden=!panel.hidden}}
function decorate(){statusCards();hudTrends();takeoverNotice();birthStates();postgameChronicle()}
window.addEventListener("ic:snapshot",ev=>{latest=(ev as CustomEvent<Detail>).detail;schedule()});
new MutationObserver(schedule).observe(document.body,{childList:true,subtree:true});schedule();