import type{PlayerSnapshot,RoomSnapshot,WorldEventOccurrence}from"./types.js";
type Detail={room:RoomSnapshot|null;player:PlayerSnapshot|null};
const w=window as any;let latest:Detail={room:null,player:null},profileCharacterId:string|null=null,scheduled=false,eventFilter="all";
function schedule(){if(scheduled)return;scheduled=true;queueMicrotask(()=>{scheduled=false;decorate()})}
const game=()=>latest.room?.game;
function focusResidenceForCharacter(characterId:string|null|undefined){if(!characterId)return;const c=game()?.characters.find(x=>x.characterId===characterId),rid=c?.currentResidenceId;if(!rid)return;document.querySelector<HTMLElement>(`.residence-map-marker[data-residence-id="${CSS.escape(rid)}"]`)?.click()}
function marriageFromProfile(){const panel=document.querySelector<HTMLElement>(".residence-authoritative-panel");if(!panel||!profileCharacterId)return;const candidate=latest.player?.marriageCandidates?.find((x:any)=>x.characterId===profileCharacterId);let btn=panel.querySelector<HTMLButtonElement>("[data-profile-marriage]");if(!candidate){btn?.remove();return}if(!btn){btn=document.createElement("button");btn.dataset.profileMarriage="1";btn.className="profile-marriage-action";panel.appendChild(btn)}const canSend=!!latest.player?.canSendMarriage,text=canSend?"CẦU HÔN":"CÓ THỂ GỬI NGOÀI LƯỢT CỦA BẠN",title=canSend?"":"Lời mời kết hôn được gửi ngoài lượt kinh tế của bạn.",sig=`${profileCharacterId}:${canSend?1:0}`;if(btn.dataset.profileStateSig===sig)return;btn.dataset.profileStateSig=sig;if(btn.dataset.target!==profileCharacterId)btn.dataset.target=profileCharacterId;if(btn.disabled===canSend)btn.disabled=!canSend;if(btn.textContent!==text)btn.textContent=text;if(btn.title!==title)btn.title=title;if(!canSend){btn.onclick=null;return}btn.onclick=async()=>{const t=w.__icTransport;if(!t?.action)return;btn!.disabled=true;try{const r=await t.action({type:"marriage:propose",targetCharacterId:profileCharacterId});const resultText=r?.ok?"ĐÃ GỬI LỜI MỜI":"KHÔNG THỂ GỬI";if(btn!.textContent!==resultText)btn!.textContent=resultText}finally{window.setTimeout(()=>{if(btn){const allowed=!!latest.player?.canSendMarriage,nextText=allowed?"CẦU HÔN":"CÓ THỂ GỬI NGOÀI LƯỢT CỦA BẠN";btn.disabled=!allowed;if(btn.textContent!==nextText)btn.textContent=nextText}},1200)}}}
function queueOldCharacter(){const b=document.querySelector<HTMLElement>("[data-old-character]"),me=latest.room?.players.find(x=>x.playerId===latest.player?.playerId);if(!b||!me?.aiTakeoverCharacterId||b.dataset.residenceBound==="1")return;b.dataset.residenceBound="1";b.onclick=e=>{e.preventDefault();e.stopPropagation();focusResidenceForCharacter(me.aiTakeoverCharacterId)}}
function minimapViewport(){const map=document.querySelector<HTMLElement>(".world-map"),view=document.querySelector<HTMLElement>(".approved-minimap .mini-viewport");if(!map||!view)return;const scale=Math.max(.8,Math.min(1.35,Number(map.style.getPropertyValue("--map-scale"))||1)),size=Math.max(35,Math.min(100,100/scale));const sig=size.toFixed(2);if(view.dataset.zoomSig===sig)return;view.dataset.zoomSig=sig;view.style.width=`${size}%`;view.style.height=`${size}%`;view.style.left=`${(100-size)/2}%`;view.style.top=`${(100-size)/2}%`}
function eventCategories(ev:WorldEventOccurrence){const s=new Set<string>(["event"]);for(const x of ev.impacts){if(x.system==="GOVERNMENT")s.add("government");if(x.system==="BIRTH")s.add("family")}return s}
function chronicleFilters(){const box=document.querySelector<HTMLElement>(".structured-world-events"),events=game()?.worldEventOccurrences||[];if(!box)return;let nav=box.querySelector<HTMLElement>(".world-event-filters");if(!nav){nav=document.createElement("nav");nav.className="world-event-filters";nav.innerHTML=`<button data-event-filter="all">TẤT CẢ</button><button data-event-filter="event">SỰ KIỆN</button><button data-event-filter="population">DÂN SỐ</button><button data-event-filter="government">CHÍNH PHỦ</button><button data-event-filter="family">GIA ĐÌNH</button>`;box.insertBefore(nav,box.children[1]||null);nav.querySelectorAll<HTMLButtonElement>("[data-event-filter]").forEach(b=>b.onclick=()=>{eventFilter=b.dataset.eventFilter||"all";applyFilter()})}applyFilter();function applyFilter(){nav!.querySelectorAll<HTMLButtonElement>("[data-event-filter]").forEach(b=>b.classList.toggle("active",b.dataset.eventFilter===eventFilter));for(const row of box!.querySelectorAll<HTMLElement>("[data-world-event-id]")){const ev=events.find(x=>x.id===row.dataset.worldEventId),cats=ev?eventCategories(ev):new Set<string>();row.hidden=eventFilter!=="all"&&!cats.has(eventFilter)}let empty=box!.querySelector<HTMLElement>(".event-filter-empty");const visible=[...box!.querySelectorAll<HTMLElement>("[data-world-event-id]")].some(x=>!x.hidden);if(!visible&&eventFilter!=="all"){if(!empty){empty=document.createElement("p");empty.className="event-filter-empty";box!.appendChild(empty)}if(empty.textContent!=="Không có mục có cấu trúc authoritative cho bộ lọc này.")empty.textContent="Không có mục có cấu trúc authoritative cho bộ lọc này."}else empty?.remove()}}
function decorate(){marriageFromProfile();queueOldCharacter();minimapViewport();chronicleFilters()}
document.addEventListener("click",ev=>{const el=ev.target as HTMLElement|null;if(!el)return;const resident=el.closest<HTMLElement>("[data-resident-character]"),related=el.closest<HTMLElement>("[data-related-character]");if(resident)profileCharacterId=resident.dataset.residentCharacter||null;else if(related)profileCharacterId=related.dataset.relatedCharacter||null;else if(el.closest("[data-residence-back],[data-residence-close]"))profileCharacterId=null;if(el.closest("[data-event-chronicle]"))window.setTimeout(()=>{document.querySelector<HTMLElement>('[data-chronicle="world"]')?.click();window.setTimeout(schedule,0)},0)},true);
window.addEventListener("ic:snapshot",ev=>{latest=(ev as CustomEvent<Detail>).detail;if(latest.player?.queuePosition==null&&latest.player?.character?.id&&profileCharacterId===latest.player.character.id)profileCharacterId=null;schedule()});
new MutationObserver(schedule).observe(document.body,{childList:true,subtree:true});schedule();
