import{GameTransport}from"./transport.js";
import type{PlayerSnapshot,RoomSnapshot}from"./types.js";

type Detail={room:RoomSnapshot|null;player:PlayerSnapshot|null};
const w=window as any;
let latest:Detail={room:null,player:null};
let scheduled=false;
let govTab:"overview"|"social"|"intervention"="overview";
let chronicleTab:"journey"|"world"="journey";
let worldMode:"timeline"|"indicators"="timeline";
const vi=(x:any)=>Number.isFinite(Number(x))?Number(x).toLocaleString("vi-VN"):"—";
const pct=(x:any)=>Number.isFinite(Number(x))?`${(Number(x)*100).toFixed(1)}%`:"—";
const esc=(x:any)=>String(x??"").replace(/[&<>\"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[c]!));
const status=(x:any)=>x==="noble"?"Quý tộc":x==="middle"?"Trung lưu":"Bình dân";

for(const key of["createRoom","joinRoom","reconnectRoom","getState","start","replay","action"] as const){
  const proto=GameTransport.prototype as any,orig=proto[key];
  if(typeof orig==="function"&&!orig.__approvedWrapped){
    const wrapped=function(this:GameTransport,...args:any[]){w.__icTransport=this;return orig.apply(this,args)};
    wrapped.__approvedWrapped=true;proto[key]=wrapped;
  }
}
const transport=()=>w.__icTransport as GameTransport|undefined;
function schedule(){if(scheduled)return;scheduled=true;queueMicrotask(()=>{scheduled=false;decorate()})}
function portrait(seed:string){let h=0;for(const c of seed)h=(h*31+c.charCodeAt(0))>>>0;return`./public/assets/ui/v1/portraits/base_${String(h%8+1).padStart(2,"0")}.png`}
function playerName(id:string|null|undefined){return latest.room?.players.find(p=>p.playerId===id)?.displayName||"Người chơi"}
function characterName(id:string|null|undefined){const c=latest.room?.game?.characters.find(x=>x.characterId===id);if(!c)return"Cư dân";const p=latest.room?.players.find(x=>x.activeCharacterId===id||x.aiTakeoverCharacterId===id||x.playerId===c.ownerId);return p?.displayName||(c.npc?"Cư dân NPC":"Cư dân")}
function localCharacter(){const id=latest.player?.character?.id;return latest.room?.game?.characters.find(c=>c.characterId===id)||null}
function currentScore(){const id=latest.player?.playerId;return latest.room?.game?.rankings.find(x=>x.playerId===id)?.average??0}
function toast(text:string){let x=document.querySelector<HTMLElement>(".approved-toast");if(!x){x=document.createElement("div");x.className="approved-toast";document.body.appendChild(x)}x.textContent=text;x.hidden=false;window.setTimeout(()=>{if(x)x.hidden=true},2200)}

function landing(){
  const root=document.querySelector<HTMLElement>(".landing-screen");if(!root)return;
  root.classList.add("approved-landing");
  const brand=root.querySelector(".brand-lockup");brand?.querySelector("p")?.remove();
  if(!root.querySelector(".landing-credit")){const old=brand?.querySelector("small");if(old){old.className="landing-credit";root.appendChild(old)}}
  if(!root.querySelector(".approved-key-art")){const art=document.createElement("section");art.className="approved-key-art";art.setAttribute("aria-hidden","true");art.innerHTML=`<div class="key-world"><i class="key-government"></i><i class="key-home a"></i><i class="key-home b"></i></div><div class="key-chibis">${["a","b","c"].map(x=>`<i style="background-image:url('${portrait(`landing-${x}`)}')"></i>`).join("")}</div>`;root.appendChild(art)}
  const recover=root.querySelector<HTMLElement>("#recover");
  if(recover&&!recover.closest(".approved-reconnect")){const code=(recover.textContent?.match(/[A-Z0-9]{6}/)||[])[0]||"";const card=document.createElement("aside");card.className="approved-reconnect";card.innerHTML=`<b>KẾT NỐI LẠI PHÒNG ${esc(code)}</b><p>NHÂN VẬT CŨ SẼ TIẾP TỤC DO NPC ĐIỀU KHIỂN · BẠN SẼ VÀO CUỐI HÀNG CHỜ</p>`;recover.textContent="KẾT NỐI LẠI";recover.parentElement?.insertBefore(card,recover);card.appendChild(recover)}
}

function lobby(){
  const root=document.querySelector<HTMLElement>(".lobby-screen"),r=latest.room;if(!root||!r)return;root.classList.add("approved-lobby");
  const pin=root.querySelector<HTMLElement>(".room-pin");
  if(pin&&!root.querySelector("#copy-room-code")){const b=document.createElement("button");b.id="copy-room-code";b.textContent="SAO CHÉP MÃ";b.onclick=async()=>{try{await navigator.clipboard.writeText(r.code);toast("ĐÃ SAO CHÉP MÃ PHÒNG")}catch{toast("Không thể sao chép tự động — hãy chọn mã phòng.")}};pin.insertAdjacentElement("afterend",b)}
  const roster=root.querySelector<HTMLElement>(".roster");if(roster){roster.classList.add("roster-grid-shell");roster.querySelectorAll<HTMLElement>(".player-row").forEach((row,i)=>{if(row.dataset.approved==="1")return;row.dataset.approved="1";row.classList.add("lobby-person");const p=r.players[i];const face=document.createElement("span");face.className="lobby-portrait";face.style.backgroundImage=`url('${portrait(p?.playerId||String(i))}')`;face.innerHTML=`<i class="connection-dot ${p?.connected?"online":"offline"}"></i>${p?.host?`<i class="host-seal" title="Chủ phòng"></i>`:""}`;row.prepend(face);const small=row.querySelector("small");if(small)small.textContent=p&&!p.connected?"MẤT KẾT NỐI":""})}
  const side=root.querySelector<HTMLElement>(".lobby-side");side?.classList.add("society-start-strip");
  if(side&&!side.querySelector("#start")&&!side.querySelector(".approved-host-wait")){const wait=document.createElement("aside");wait.className="approved-host-wait";wait.textContent="ĐANG CHỜ CHỦ PHÒNG BẮT ĐẦU…";side.appendChild(wait)}
}

function hud(){
  const root=document.querySelector<HTMLElement>(".world-hud"),g=latest.room?.game;if(!root||!g)return;root.classList.add("approved-hud");
  const direct=[...root.querySelectorAll<HTMLElement>(":scope > span")];
  if(!root.querySelector(".hud-round-year")&&direct.length>=7){const ry=document.createElement("div");ry.className="hud-cluster hud-round-year";ry.append(direct[0]!,direct[1]!);const society=document.createElement("div");society.className="hud-cluster hud-society";society.append(direct[2]!,direct[3]!,direct[4]!);const event=direct[5]!,phase=direct[6]!;phase.classList.add("hud-phase");root.prepend(ry,society);if(g.eventName){event.classList.add("world-event-banner");event.querySelector("small")!.textContent="SỰ KIỆN THẾ GIỚI";if(g.policy.economicIncomeFactor!=null&&g.policy.economicIncomeFactor!==1)event.insertAdjacentHTML("beforeend",`<em>Hệ số thu nhập ${vi(g.policy.economicIncomeFactor)}</em>`)}else event.remove()}
  root.querySelector('[data-help]')?.remove();
  if(!root.querySelector(".hud-settings")){const b=document.createElement("button");b.className="hud-settings";b.textContent="CÀI ĐẶT";b.setAttribute("aria-label","Cài đặt");b.onclick=()=>toast("Cài đặt chưa có contract chức năng trong Client hiện tại.");root.appendChild(b)}
}

function world(){
  const map=document.querySelector<HTMLElement>(".world-map");if(!map)return;map.classList.add("approved-world");
  const controls=map.querySelector<HTMLElement>(".map-controls");controls?.querySelectorAll<HTMLElement>('[data-panel="government"],[data-panel="residence"]').forEach(x=>x.remove());
  if(!map.querySelector(".approved-minimap")){const mini=document.createElement("aside");mini.className="approved-minimap";mini.innerHTML=`<div class="mini-map"><i class="mini-road a"></i><i class="mini-road b"></i><button data-mini="gov" aria-label="Chính phủ"></button>${latest.player?.queuePosition?"":`<button data-mini="home" aria-label="Nhà"></button>`}<span class="mini-viewport"></span></div>`;mini.querySelector<HTMLElement>('[data-mini="gov"]')!.onclick=()=>map.querySelector<HTMLElement>(".landmark.gov")?.focus();mini.querySelector<HTMLElement>('[data-mini="home"]')?.addEventListener("click",()=>map.querySelector<HTMLElement>(".landmark.home")?.focus());map.appendChild(mini)}
  const track=document.querySelector<HTMLElement>(".turn-track");if(track){track.classList.add("approved-turn-track");if(!track.querySelector(".turn-line")){const line=document.createElement("i");line.className="turn-line";track.prepend(line)}track.querySelectorAll<HTMLElement>(".turn-token").forEach((x,i)=>{if(x.querySelector(".turn-avatar"))return;const a=document.createElement("span");a.className="turn-avatar";a.style.backgroundImage=`url('${portrait(x.dataset.profile||String(i))}')`;x.prepend(a)})}
}

function phase(){
  const g=latest.room?.game;if(!g)return;
  const mandatory=document.querySelector<HTMLElement>(".mandatory-card");if(mandatory){mandatory.classList.add("approved-phase-card","approved-mandatory");mandatory.querySelectorAll(".metrics").forEach(x=>x.remove())}
  const s=document.querySelector<HTMLElement>(".status-card");if(s){s.classList.add("approved-phase-card","approved-status");const small=s.querySelector("small");if(small)small.textContent=localCharacter()?.married?"CHỌN CHO HỘ GIA ĐÌNH":"CHỌN ĐỊA VỊ CHO VÒNG SAU";if(!s.querySelector(".status-effective")){const p=document.createElement("p");p.className="status-effective";p.textContent="HIỆU LỰC VÒNG SAU";s.insertBefore(p,s.querySelector(".status-grid"))}const left=Math.max(0,Math.ceil(((g.phaseDeadlineAt||0)-Date.now())/1000));let warn=s.querySelector<HTMLElement>(".status-time-warning");if(left<5&&!warn){warn=document.createElement("p");warn.className="status-time-warning";warn.textContent="HẾT GIỜ: hệ thống sẽ ưu tiên giữ địa vị hiện tại nếu hợp lệ; nếu không sẽ tự hạ bậc.";s.appendChild(warn)}else if(left>=5)warn?.remove()}
  const dock=document.querySelector<HTMLElement>(".voluntary-dock");if(dock){dock.classList.add("approved-voluntary");dock.querySelector("strong")?.remove();dock.querySelector<HTMLElement>('[data-panel="marriage"]')?.remove();const active=document.querySelector<HTMLElement>(".feature-sheet[data-tutorial-zone]")?.dataset.tutorialZone||"";dock.querySelectorAll<HTMLElement>("[data-panel]").forEach(x=>x.classList.toggle("active",x.dataset.panel===active))}
}

function market(){
  const root=document.querySelector<HTMLElement>('.feature-sheet[data-tutorial-zone="market"]'),g=latest.room?.game;if(!root||!g||root.dataset.approved==="1")return;root.dataset.approved="1";root.classList.add("approved-market");const shared=root.querySelector("#units")?.closest("label") as HTMLElement|null;if(shared)shared.hidden=true;const me=localCharacter();
  root.querySelectorAll<HTMLElement>(".resource-card").forEach((card,i)=>{const type=(i<3?"renewable":"nonrenewable") as "renewable"|"nonrenewable",grade=(["low","mid","high"] as const)[i%3]!,owned=type==="renewable"?me?.renewableResources?.[grade]:me?.nonRenewableResources?.[grade];card.querySelector("dl")?.insertAdjacentHTML("beforeend",`<dt>Sở hữu</dt><dd>${vi(owned||0)}</dd>`);const buy=card.querySelector<HTMLElement>("[data-buy]");if(!buy)return;buy.hidden=true;const q=document.createElement("div");q.className="qty-controls";q.innerHTML=`<button data-step="-1">−</button><input type="number" min="1" value="1"><button data-step="1">+</button><button disabled title="Chưa có MAX authoritative">MAX</button><button data-submit>MUA</button>`;q.querySelectorAll<HTMLElement>("[data-step]").forEach(b=>b.onclick=()=>{const input=q.querySelector<HTMLInputElement>("input")!;input.value=String(Math.max(1,(Number(input.value)||1)+Number(b.dataset.step)))});q.querySelector<HTMLElement>("[data-submit]")!.onclick=()=>{const old=root.querySelector<HTMLInputElement>("#units")!;old.value=q.querySelector<HTMLInputElement>("input")!.value;buy.click()};card.appendChild(q)});
  root.insertAdjacentHTML("beforeend",`<p class="production-note">TÀI NGUYÊN MUA VÒNG NÀY ĐƯỢC XỬ LÝ/SẢN XUẤT TỪ VÒNG SAU KHI NHÂN VẬT ĐỦ ĐIỀU KIỆN.</p>`)
}

function recovery(){
  const root=document.querySelector<HTMLElement>('.feature-sheet[data-tutorial-zone="recovery"]'),p=latest.player;if(!root||root.dataset.approved==="1")return;root.dataset.approved="1";root.classList.add("approved-recovery");const oldInput=root.querySelector<HTMLInputElement>("#recover-units");if(oldInput?.closest("label"))oldInput.closest<HTMLElement>("label")!.hidden=true;
  root.querySelectorAll<HTMLElement>(".recovery-row[data-recover]").forEach((action,i)=>{const grade=action.dataset.recover||"low",quote=p?.recoveryQuotes.find(x=>x.grade===grade),orig=action.onclick;const card=document.createElement("article");card.className="recovery-card";action.parentElement!.insertBefore(card,action);card.innerHTML=quote?`<div><h3>${grade.toUpperCase()}</h3><dl><dt>Pool</dt><dd>${vi(quote.currentPool)}</dd><dt>Sức chứa</dt><dd>${vi(quote.carryingCapacity)}</dd><dt>Pending vòng sau</dt><dd>${vi(quote.pendingNextRound)}</dd><dt>Còn sức chứa</dt><dd>${vi(quote.capacityRemaining)}</dd><dt>Chi phí/đơn vị</dt><dd>${vi(quote.costPerUnit)}</dd></dl><progress max="${Math.max(1,quote.carryingCapacity)}" value="${quote.currentPool}"></progress></div>`:`<div><h3>${grade.toUpperCase()}</h3><p>Chưa có quote authoritative.</p></div>`;const controls=document.createElement("div");controls.className="qty-controls";controls.innerHTML=`<button data-minus>−</button><input type="number" min="1" value="1"><button data-plus>+</button><button disabled title="Chưa có MAX authoritative">MAX</button>`;const input=controls.querySelector<HTMLInputElement>("input")!;controls.querySelector<HTMLElement>("[data-minus]")!.onclick=()=>input.value=String(Math.max(1,(Number(input.value)||1)-1));controls.querySelector<HTMLElement>("[data-plus]")!.onclick=()=>input.value=String(Math.max(1,(Number(input.value)||1)+1));card.append(controls,action);action.textContent="PHỤC HỒI";action.onclick=ev=>{if(oldInput)oldInput.value=input.value;orig?.call(action,ev)}});
  root.insertAdjacentHTML("beforeend",`<footer class="panel-footer">Cash ${vi(p?.financial?.cash)} · Quota còn lại ${vi(p?.financial?.spendingRemaining)} · HIỆU LỰC VÒNG SAU</footer>`)
}

function support(){
  const root=document.querySelector<HTMLElement>('.feature-sheet[data-tutorial-zone="support"]'),p=latest.player;if(!root||!p||root.dataset.approved==="1")return;root.dataset.approved="1";root.classList.add("approved-support");const select=root.querySelector<HTMLSelectElement>("#support-target"),amount=root.querySelector<HTMLInputElement>("#amount"),send=root.querySelector<HTMLElement>("#support-send");if(!select||!amount||!send)return;const deck=document.createElement("div");deck.className="support-card-grid";
  for(const target of p.eligibleSupportTargets){const card=document.createElement("article");card.className="support-card";card.innerHTML=`<div class="person-head"><span style="background-image:url('${portrait(target.characterId)}')"></span><div><b>${esc(characterName(target.characterId))}</b><small>${target.relation==="parent"?"CHA/MẸ":"CON"} · ${esc(target.ageLabel)} · ${status(target.status)}</small></div></div><div class="qty-controls"><button data-minus>−</button><input type="number" min="1" value="1"><button data-plus>+</button><button disabled title="Chưa có MAX authoritative">MAX</button><button data-send>CHU CẤP</button></div>`;const input=card.querySelector<HTMLInputElement>("input")!;card.querySelector<HTMLElement>("[data-minus]")!.onclick=()=>input.value=String(Math.max(1,(Number(input.value)||1)-1));card.querySelector<HTMLElement>("[data-plus]")!.onclick=()=>input.value=String(Math.max(1,(Number(input.value)||1)+1));card.querySelector<HTMLElement>("[data-send]")!.onclick=()=>{select.value=target.characterId;amount.value=input.value;send.click()};deck.appendChild(card)}
  select.closest<HTMLElement>("label")!.hidden=true;amount.closest<HTMLElement>("label")!.hidden=true;send.hidden=true;root.insertBefore(deck,root.querySelector("p"));root.insertAdjacentHTML("afterbegin",`<p class="support-note">HỖ TRỢ TỰ NGUYỆN THÊM · Chu cấp bắt buộc được xử lý ở phase Bắt buộc.</p>`)
}

function birth(){const root=document.querySelector<HTMLElement>('.feature-sheet[data-tutorial-zone="birth"]'),g=latest.room?.game,p=latest.player;if(!root||!g||!p)return;root.classList.add("approved-birth");const left=Math.max(0,Math.ceil(((g.phaseDeadlineAt||0)-Date.now())/1000));let warn=root.querySelector<HTMLElement>(".birth-default-warning");if(left<10&&p.incomingBirthProposals.length&&!warn){warn=document.createElement("p");warn.className="birth-default-warning";warn.textContent="CÒN DƯỚI 10 GIÂY: nếu không phản hồi, máy chủ sẽ áp dụng mặc định Đồng ý theo luật authoritative.";root.prepend(warn)}else if(left>=10)warn?.remove()}

async function cancelMarriage(id:string){const t=transport();if(!t)return toast("Chưa có phiên kết nối để gửi yêu cầu.");const r=await t.action({type:"marriage:cancel",proposalId:id});toast(r.ok?"ĐÃ HỦY LỜI CẦU HÔN":r.error||"Không thể hủy")}
function marriage(){const root=document.querySelector<HTMLElement>('.feature-sheet[data-tutorial-zone="marriage"]'),p=latest.player;if(!root||!p)return;root.classList.add("approved-marriage");if(root.querySelector(".outgoing-proposals")||!p.outgoingMarriageProposals.length)return;const deck=document.createElement("section");deck.className="outgoing-proposals";deck.innerHTML=`<h3>LỜI CẦU HÔN ĐÃ GỬI</h3>${p.outgoingMarriageProposals.map((x:any)=>`<article><b>${esc(characterName(x.targetCharacterId))}</b><small>Đang chờ · không hết hạn</small><button data-cancel="${esc(x.id)}">HỦY LỜI CẦU HÔN</button></article>`).join("")}`;deck.querySelectorAll<HTMLElement>("[data-cancel]").forEach(x=>x.onclick=()=>void cancelMarriage(x.dataset.cancel||""));root.appendChild(deck)}

function residence(){const root=document.querySelector<HTMLElement>(".residence-sheet"),g=latest.room?.game;if(!root||!g)return;root.classList.add("approved-residence");const selectedId=(document.querySelector<HTMLElement>("[data-profile].active")?.dataset.profile)||latest.player?.character?.id;const c=g.characters.find(x=>x.characterId===selectedId);if(c?.immigrant&&!root.querySelector(".immigrant-label")){const b=document.createElement("p");b.className="immigrant-label";b.textContent="NGƯỜI NHẬP CƯ";root.appendChild(b)}if(c&&c.ageStage>=7&&!root.querySelector(".elderly-health")){const box=document.createElement("section");box.className="elderly-health";box.innerHTML=`<h3>SỨC KHỎE TUỔI GIÀ</h3><dl><dt>Y tế phải trả</dt><dd>${vi(c.elderlyMedicalDue)}</dd><dt>Đã trả</dt><dd>${vi(c.elderlyMedicalPaid)}</dd><dt>Rủi ro tử vong gần nhất</dt><dd>${pct(c.mortalityRisk)}</dd></dl>`;root.appendChild(box)}}

function government(){
  const root=document.querySelector<HTMLElement>(".government-sheet"),g=latest.room?.game;if(!root||!g)return;const gov=g.government||{},ss=g.socialSecurity||{},sig=`${govTab}:${g.round}:${gov.budget}:${g.debt}:${ss.pensionPaid}`;if(root.dataset.approvedSig===sig)return;root.dataset.approvedSig=sig;const close=root.querySelector<HTMLElement>(".panel-close")?.outerHTML||"";const total=Number(ss.payg||0)+Number(ss.support||0)+Number(ss.pensionReserve||0);const tabs=`<nav class="drawer-tabs">${[["overview","TỔNG QUAN"],["social","AN SINH"],["intervention","CAN THIỆP"]].map(([k,v])=>`<button data-approved-gov="${k}" class="${govTab===k?"active":""}">${v}</button>`).join("")}</nav>`;let body="";
  if(govTab==="overview")body=`<div class="gov-metrics"><span>Ngân sách<b>${vi(gov.budget)}</b></span><span>Nợ / Trần<b>${vi(g.debt)} / ${vi(gov.debtCeiling)}</b></span><span>Dự trữ sàn<b>${vi(gov.reserveFloor)}</b></span><span>Thuế vòng này<b>${vi(gov.taxCollectedThisRound)}</b></span></div>${gov.fiscalCrisis?`<aside class="crisis-warning">KHỦNG HOẢNG TÀI KHÓA</aside>`:""}`;
  if(govTab==="social")body=`<section class="social-fund"><h3>TỔNG QUỸ AN SINH</h3><b>${vi(total)}</b><small>Chỉ tổng hợp hiển thị; các quỹ nền vẫn là cơ chế riêng.</small></section><dl class="detail-list"><dt>Mục tiêu lương hưu</dt><dd>${vi(ss.pensionTarget)}</dd><dt>Đã trả</dt><dd>${vi(ss.pensionPaid)}</dd><dt>Nhà nước chuyển</dt><dd>${vi(ss.pensionStateTransfer)}</dd><dt>Tỷ lệ chi trả</dt><dd>${pct(ss.pensionPayoutRatio)}</dd><dt>Người lao động</dt><dd>${vi(ss.workers)}</dd><dt>Người cao tuổi</dt><dd>${vi(ss.elders)}</dd><dt>Khủng hoảng</dt><dd>${ss.pensionCrisis?"CÓ":"KHÔNG"}</dd></dl>`;
  if(govTab==="intervention")body=`<h3>CAN THIỆP · CHỈ ĐỌC</h3>${(gov.interventions||[]).map((x:any)=>`<p>${esc(typeof x==="string"?x:x.detail||x.type)}</p>`).join("")||"<p>Không có can thiệp vòng này.</p>"}<h3>LỊCH SỬ NGẮN</h3>${(gov.fiscalHistory||[]).slice(-5).reverse().map((x:any)=>`<p>Vòng ${vi(x.round)} · Ngân sách ${vi(x.closingBudget)} · Nợ ${vi(x.closingDebt)}</p>`).join("")}`;
  root.innerHTML=`${close}<h2>CHÍNH PHỦ</h2>${tabs}${body}`;root.querySelectorAll<HTMLElement>("[data-approved-gov]").forEach(x=>x.onclick=()=>{govTab=x.dataset.approvedGov as any;root.dataset.approvedSig="";government()})
}

function journeyHtml(){const h=latest.player?.history;if(!h)return"<p>Chưa có lịch sử.</p>";const groups:Array<{n:number;events:any[]}>=[];let current:{n:number;events:any[]}|null=null;for(const ev of h.events||[]){if(ev.type==="life_start"||ev.type==="reincarnation"||!current){current={n:groups.length+1,events:[]};groups.push(current)}current.events.push(ev)}const trend=(h.scoreSnapshots||[]).map((x:any)=>`<i style="--v:${Math.max(2,Math.min(100,Number(x.scoreAssets)||0))}" title="V${x.round}: ${vi(x.scoreAssets)}"></i>`).join("");return`<section class="score-block"><small>ĐIỂM TÀI SẢN TRUNG BÌNH QUA CÁC KIẾP</small><b>${vi(currentScore())}</b><div class="score-trend">${trend}</div></section>${groups.map(g=>`<section class="life-group"><h3>KIẾP #${g.n}</h3>${g.events.map(ev=>`<p><b>Vòng ${vi(ev.round)} · Năm ${vi(ev.year)}</b><span>${esc(ev.detail)}</span></p>`).join("")}</section>`).join("")}`}
function worldHtml(){const hs=latest.room?.game?.historySnapshots||[];if(worldMode==="timeline")return`<nav class="world-mode"><button data-world-mode="timeline" class="active">DÒNG THỜI GIAN</button><button data-world-mode="indicators">CHỈ SỐ</button></nav>${hs.slice().reverse().map((x:any)=>`<p class="world-history-row"><b>Vòng ${vi(x.round)} · Năm ${vi(x.year)}</b><span>Dân số ${vi(x.population)} · Lạm phát ${pct(x.inflationRate)} · Nợ ${vi(x.publicDebt)}${x.eventName?` · Sự kiện ${esc(x.eventName)}`:""}</span></p>`).join("")||"<p>Chưa có snapshot lịch sử.</p>"}`;const last=hs.slice(-12),vals=(key:string)=>last.map((x:any)=>vi(x[key]??0)).join(" → ");return`<nav class="world-mode"><button data-world-mode="timeline">DÒNG THỜI GIAN</button><button data-world-mode="indicators" class="active">CHỈ SỐ</button></nav><div class="indicator-grid">${[["population","DÂN SỐ"],["inflationRate","LẠM PHÁT"],["publicDebt","NỢ CÔNG"],["totalAssets","TỔNG TÀI SẢN"],["pensionPayoutRatio","TỶ LỆ LƯƠNG HƯU"]].map(([k,label])=>`<div><small>${label}</small><b>${vals(k)||"—"}</b></div>`).join("")}</div>`}
function chronicle(){const root=document.querySelector<HTMLElement>(".history-sheet");if(!root)return;const sig=`${chronicleTab}:${worldMode}:${latest.room?.game?.round}:${latest.player?.history?.events?.length||0}`;if(root.dataset.approvedSig===sig)return;root.dataset.approvedSig=sig;const close=root.querySelector<HTMLElement>(".panel-close")?.outerHTML||"";root.innerHTML=`${close}<h2>NIÊN SỬ</h2><nav class="chronicle-tabs"><button data-chronicle="journey" class="${chronicleTab==="journey"?"active":""}">HÀNH TRÌNH</button><button data-chronicle="world" class="${chronicleTab==="world"?"active":""}">THẾ GIỚI</button></nav><div class="chronicle-body">${chronicleTab==="journey"?journeyHtml():worldHtml()}</div>`;root.querySelectorAll<HTMLElement>("[data-chronicle]").forEach(x=>x.onclick=()=>{chronicleTab=x.dataset.chronicle as any;root.dataset.approvedSig="";chronicle()});root.querySelectorAll<HTMLElement>("[data-world-mode]").forEach(x=>x.onclick=()=>{worldMode=x.dataset.worldMode as any;root.dataset.approvedSig="";chronicle()})}

function queue(){const root=document.querySelector<HTMLElement>(".queue-card"),p=latest.player,r=latest.room;if(!root||!p||!r)return;const pos=p.queuePosition??0,old=r.players.find(x=>x.playerId===p.playerId)?.aiTakeoverCharacterId,sig=`${pos}:${old||""}`;if(root.dataset.approvedSig===sig)return;root.dataset.approvedSig=sig;root.classList.add("approved-queue");root.innerHTML=`<small>CHẾ ĐỘ KHÁN GIẢ</small><h1>HÀNG CHỜ #${pos}</h1><p>Bạn sẽ nhận Character mới khi máy chủ gán một newborn đủ điều kiện. Không có dự đoán thời gian chờ.</p><b>Human phía trước: ${Math.max(0,pos-1)}</b>${old?`<button data-old-character>NHÂN VẬT CŨ · NPC ĐIỀU KHIỂN</button>`:""}<nav><button data-public-government>CHÍNH PHỦ</button><button data-public-chronicle>NIÊN SỬ</button></nav>`;root.querySelector<HTMLElement>("[data-public-government]")!.onclick=()=>document.querySelector<HTMLElement>('.landmark.gov')?.click();root.querySelector<HTMLElement>("[data-public-chronicle]")!.onclick=()=>document.querySelector<HTMLElement>('[data-panel="chronicle"]')?.click();root.querySelector<HTMLElement>("[data-old-character]")?.addEventListener("click",()=>toast("Nhân vật cũ tiếp tục do NPC điều khiển và không thể được reclaim."))}

function endReport(){const root=document.querySelector<HTMLElement>(".end-screen"),g=latest.room?.game,p=latest.player;if(!root||!g||!p||root.dataset.approved==="1")return;root.dataset.approved="1";document.querySelector<HTMLElement>(".world-hud")?.remove();const rank=g.rankings||[],ext=/tuyệt chủng|extinct/i.test(g.endingReason||""),winner=rank[0],hist=p.history||{},meIndex=rank.findIndex(x=>x.playerId===p.playerId);const podium=!ext?rank.slice(0,3).map((x,i)=>`<article class="podium-${i+1}"><b>#${i+1}</b><strong>${esc(playerName(x.playerId))}</strong><span>${vi(x.average)}</span></article>`).join(""):"";const list=rank.map((x,i)=>`<p class="rank-row"><b>#${i+1}</b><span>${esc(playerName(x.playerId))}${x.activeRounds===0?` <em>CHƯA CÓ KIẾP SỐNG · 0 VÒNG HOẠT ĐỘNG</em>`:""}</span><strong>${vi(x.average)}</strong></p>`).join("");root.innerHTML=`<div class="end-world-backdrop"></div><section class="parchment approved-end-card">${ext?`<header class="extinction-result"><h1>XÃ HỘI ĐÃ TUYỆT CHỦNG</h1><h2>THẤT BẠI CHUNG</h2></header>`:`<header class="winner-result"><small>NGƯỜI CHIẾN THẮNG</small><h1>${esc(playerName(winner?.playerId))}</h1><b>${vi(winner?.average)}</b></header>`}<p class="score-explain"><b>ĐIỂM TÀI SẢN TRUNG BÌNH QUA CÁC KIẾP</b><br>Điểm được tính từ tài sản HHA được ghi nhận trong các vòng/kiếp sống hoạt động, không chỉ từ tiền mặt.</p><section class="personal-recap"><h2>HÀNH TRÌNH CỦA BẠN</h2><span>Hạng <b>${meIndex>=0?meIndex+1:"—"}</b></span><span>Điểm TB <b>${vi(currentScore())}</b></span><span>Kiếp sống <b>${vi(hist.lives)}</b></span><span>Đỉnh tài sản-score <b>${vi(hist.highestAssets)}</b></span><span>Địa vị cao nhất <b>${status(hist.highestStatus)}</b></span><span>Hôn nhân <b>${vi(hist.marriages)}</b></span><span>Con <b>${vi(hist.children)}</b></span></section>${podium?`<section class="end-podium">${podium}</section>`:""}<section class="full-ranking"><h2>${ext?"THỐNG KÊ HẬU KỲ":"XẾP HẠNG"}</h2>${list}</section><nav class="end-actions"><button data-final-world>XEM THẾ GIỚI CUỐI CÙNG</button>${latest.room?.hostPlayerId===p.playerId?`<button data-approved-replay class="primary">CHƠI LẠI CÙNG PHÒNG</button>`:`<aside>ĐANG CHỜ HOST</aside>`}</nav><section class="final-world-readonly" hidden><b>THẾ GIỚI CUỐI CÙNG · CHỈ ĐỌC</b><p>Dân số ${vi(g.population.total)} · Lạm phát ${pct(g.policy.inflationRate)} · Nợ công ${vi(g.debt)} · Ngân sách ${vi(g.government?.budget)}</p></section></section>`;root.querySelector<HTMLElement>("[data-final-world]")!.onclick=()=>{const x=root.querySelector<HTMLElement>(".final-world-readonly")!;x.hidden=!x.hidden};root.querySelector<HTMLElement>("[data-approved-replay]")?.addEventListener("click",async()=>{toast("BẮT ĐẦU MỘT XÃ HỘI MỚI");const t=transport();if(t)await t.replay()})}

function roundTransition(){const root=document.querySelector<HTMLElement>(".round-transition"),g=latest.room?.game;if(!root||!g)return;const last=g.historySnapshots?.[g.historySnapshots.length-1];if(last?.immigration&&!root.querySelector(".immigration-note")){const p=document.createElement("p");p.className="immigration-note";p.textContent=`NHẬP CƯ · +${vi(last.immigration)} CƯ DÂN`;root.appendChild(p)}}
function decorate(){landing();lobby();hud();world();phase();market();recovery();support();birth();marriage();residence();government();chronicle();queue();endReport();roundTransition()}
window.addEventListener("ic:snapshot",ev=>{latest=(ev as CustomEvent<Detail>).detail;schedule()});
new MutationObserver(schedule).observe(document.body,{childList:true,subtree:true});
schedule();
