import type{MandatoryQuote,PlayerSnapshot,RecoveryQuote,RoomSnapshot,StatusQuote}from"./types.js";

type SnapshotDetail={room:RoomSnapshot|null;player:PlayerSnapshot|null};
let latestSnapshot:SnapshotDetail={room:null,player:null};
const vi=(x:number)=>Number.isFinite(x)?x.toLocaleString("vi-VN"):"—";
const pct=(x:number)=>Number.isFinite(x)?`${(x*100).toFixed(1)}%`:"—";
const dominantLabel:Record<string,string>={living:"Sinh hoạt",socialContribution:"An sinh",tax:"Thuế",childSupport:"Chu cấp con",parentSupport:"Chu cấp cha/mẹ",grief:"Tang chế",medical:"Y tế"};
const statusLabel:Record<string,string>={poor:"Bình dân",middle:"Trung lưu",noble:"Quý tộc"};

export function worldEventText(room:RoomSnapshot|null){return room?.game?.eventName?.trim()||"Không có"}
export function mandatorySummary(q:MandatoryQuote|null){if(!q)return null;return{total:q.breakdown.total,cashBefore:q.cashBefore,liquidationRequired:q.liquidationRequired,liquidationProceeds:q.liquidationProceeds,cashAfterLiquidation:q.cashAfterLiquidation,projectedBankruptcy:q.projectedBankruptcy,shortfall:q.shortfall,dominantCost:dominantLabel[q.dominantCost]||q.dominantCost}}
export function recoverySummary(q:RecoveryQuote){return`${q.grade.toUpperCase()} · Pool ${vi(q.currentPool)}/${vi(q.carryingCapacity)} · Pending +${vi(q.pendingNextRound)} · Còn ${vi(q.capacityRemaining)} · ${vi(q.costPerUnit)}/đơn vị`}
export function statusSummary(q:StatusQuote|null){if(!q)return null;return{cards:q.cards.map(c=>({status:c.status,label:statusLabel[c.status]||c.status,fee:c.fee,personsCharged:c.personsCharged,affordable:c.affordable})),noble:{...q.nobleCompetition}}}
export function rememberSnapshot(detail:SnapshotDetail){latestSnapshot=detail;return latestSnapshot}
export function currentSnapshot(){return latestSnapshot}

function ensureStyle(){if(document.getElementById("display-contract-style"))return;const s=document.createElement("style");s.id="display-contract-style";s.textContent=`.server-display{margin-top:.75rem;padding:.65rem;border:2px solid #806337;background:#1f180fd9;color:#f2e3b7}.server-display h4{margin:.1rem 0 .5rem}.server-display dl{display:grid;grid-template-columns:1fr auto;gap:.3rem .7rem}.server-display dd{margin:0;text-align:right}.server-display .warning{color:#ffd08c}.server-display .danger{color:#ffb3a5}.server-quote{display:block;margin-top:.25rem;font-size:.72rem}.status-card .server-display{max-height:34vh;overflow:auto}`;document.head.appendChild(s)}
function upsert(parent:Element,html:string){let box=parent.querySelector<HTMLElement>(":scope > .server-display");if(!box){box=document.createElement("div");box.className="server-display";parent.appendChild(box)}box.innerHTML=html}

function renderEvent(room:RoomSnapshot|null){document.querySelectorAll(".world-hud>span").forEach(span=>{const small=span.querySelector("small"),b=span.querySelector("b");if(small?.textContent?.trim()==="SỰ KIỆN"&&b)b.textContent=worldEventText(room)})}
function renderMandatory(player:PlayerSnapshot|null){const root=document.querySelector(".mandatory-card");if(!root)return;const q=player?.mandatoryQuote||null;if(!q){root.querySelector(":scope > .server-display")?.remove();return}const b=q.breakdown;upsert(root,`<h4>DỰ KIẾN THEO SNAPSHOT HIỆN TẠI</h4><dl><dt>Sinh hoạt</dt><dd>${vi(b.living)}</dd><dt>An sinh</dt><dd>${vi(b.socialContribution)}</dd><dt>Thuế</dt><dd>${vi(b.tax)}</dd><dt>Chu cấp con</dt><dd>${vi(b.childSupport)}</dd><dt>Chu cấp cha/mẹ</dt><dd>${vi(b.parentSupport)}</dd><dt>Tang chế</dt><dd>${vi(b.grief)}</dd><dt>Y tế</dt><dd>${vi(b.medical)}</dd><dt><b>Tổng bắt buộc</b></dt><dd><b>${vi(b.total)}</b></dd><dt>Thu nhập ròng</dt><dd>${vi(q.netIncome)}</dd><dt>Cash trước xử lý</dt><dd>${vi(q.cashBefore)}</dd><dt>Thanh lý dự kiến</dt><dd>${q.liquidationRequired?vi(q.liquidationProceeds):"Không cần"}</dd><dt>Cash sau thanh lý dự kiến</dt><dd>${vi(q.cashAfterLiquidation)}</dd><dt>Thiếu hụt dự kiến</dt><dd>${vi(q.shortfall)}</dd><dt>Khoản lớn nhất</dt><dd>${dominantLabel[q.dominantCost]||q.dominantCost}</dd></dl><p class="${q.projectedBankruptcy?"danger":"warning"}">${q.projectedBankruptcy?"DỰ KIẾN PHÁ SẢN nếu snapshot không đổi.":"Chưa dự kiến phá sản ở snapshot này."} Kết quả cuối cùng do server giải quyết theo trạng thái tại thời điểm xử lý.</p>`)}
function renderRecovery(player:PlayerSnapshot|null){const quotes=player?.recoveryQuotes||[];document.querySelectorAll<HTMLElement>(".recovery-row[data-recover]").forEach(row=>{const q=quotes.find(x=>x.grade===row.dataset.recover);let label=row.querySelector<HTMLElement>(".server-quote");if(!q){label?.remove();return}if(!label){label=document.createElement("span");label.className="server-quote";row.appendChild(label)}label.textContent=recoverySummary(q)})}
function renderStatus(player:PlayerSnapshot|null){const root=document.querySelector(".status-card");if(!root)return;const q=player?.statusQuote||null;if(!q){root.querySelector(":scope > .server-display")?.remove();return}const cards=q.cards.map(c=>`<dt>${statusLabel[c.status]||c.status}</dt><dd>${vi(c.fee)} · ${c.personsCharged} người · ${c.affordable?"Đủ cash":"Thiếu cash"}</dd>`).join("");const n=q.nobleCompetition;upsert(root,`<h4>PHÍ & CẠNH TRANH AUTHORITATIVE</h4><dl><dt>Tài sản TB vòng</dt><dd>${vi(q.roundAverageAssets)}</dd><dt>Price Index</dt><dd>${vi(q.priceIndex)}</dd>${cards}<dt>Slot Noble</dt><dd>${n.slotsRequired}/${n.slotsTotal} cần · ${n.pendingNobleSlots} đang chờ</dd><dt>Ưu tiên</dt><dd>${n.priority.join(" → ")}</dd><dt>Turn card</dt><dd>${n.turnCard??"—"}</dd><dt>Fallback</dt><dd>${statusLabel[n.fallbackStatus]} · phí ${vi(n.middleFallbackFee)}</dd><dt>Refund tối đa tiềm năng</dt><dd>${vi(n.potentialRefund)}</dd></dl><p>Phân bổ Noble diễn ra cuối vòng; quote hiện tại không phải cam kết kết quả.</p>`)}

export function decorateSnapshot(detail:SnapshotDetail){latestSnapshot=detail;if(typeof document==="undefined")return;ensureStyle();renderEvent(detail.room);renderMandatory(detail.player);renderRecovery(detail.player);renderStatus(detail.player)}
export function redecorateLatest(){decorateSnapshot(latestSnapshot)}
if(typeof window!=="undefined"){
 window.addEventListener("ic:snapshot",e=>decorateSnapshot((e as CustomEvent<SnapshotDetail>).detail));
 document.addEventListener("click",e=>{const target=e.target as Element|null;if(target?.closest?.("[data-panel]"))window.setTimeout(redecorateLatest,0)});
}
