import{GameTransport}from"./transport.js";
import{marketAction,marriageAction,recoveryAction,supportAction}from"./action-payloads.js";
import{loadTutorial,nextCoach,saveTutorial,tutorialCopy,unlockedSteps,type TutorialState}from"./tutorial.js";
import type{Panel,Screen,TutorialStepId}from"./types.js";

const app=document.querySelector<HTMLElement>("#app")!;
const t=new GameTransport();
const pid=localStorage.getItem("ic:playerId")||crypto.randomUUID();
localStorage.setItem("ic:playerId",pid);
let screen:Screen="landing",panel:Panel="overview",tutorial:TutorialState=loadTutorial(localStorage),help=false,busy=false,msg="",err="";
let govTab:"overview"|"budget"|"debt"|"social"="overview",resultTab:"ranking"|"journey"|"world"="ranking",profileCharacterId:string|null=null;
let mapScale=1,lastRound:number|null=null,transitionRound:number|null=null,transitionTimer:number|null=null,founderBannerSeen=false;

t.onChange=()=>{if(t.room)screen=t.room.started?"game":"lobby";trackRoundTransition();render()};
t.onConnection=render;

const e=(x:any)=>String(x??"").replace(/[&<>\"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[c]!));
const n=(x:any)=>Number.isFinite(Number(x))?Number(x).toLocaleString("vi-VN"):"—";
const pc=(x:any)=>Number.isFinite(Number(x))?`${(Number(x)*100).toFixed(1)}%`:"—";
const rec=()=>{try{return JSON.parse(localStorage.getItem("ic:reconnect")||"null")}catch{return null}};
const host=()=>t.room?.hostPlayerId===pid;
const statusName=(x:any)=>x==="noble"?"Quý tộc":x==="middle"?"Trung lưu":"Bình dân";

function timer(){const a=t.room?.game?.phaseDeadlineAt;return a?`${Math.max(0,Math.ceil((a-Date.now())/1000))}s`:"—"}
setInterval(()=>{const x=document.querySelector("[data-timer]");if(x)x.textContent=timer()},250);
function trackRoundTransition(){const r=t.room?.game?.round;if(!r)return;if(lastRound==null){lastRound=r;return}if(r!==lastRound){lastRound=r;transitionRound=r;if(transitionTimer)window.clearTimeout(transitionTimer);transitionTimer=window.setTimeout(()=>{transitionRound=null;render()},2500)}}
async function run(op:()=>Promise<any>,ok=""){const pending=op();busy=true;msg=err="";render();try{const r=await pending;if(!r.ok)err=r.error||"ACTION_FAILED";else msg=ok;return r}finally{busy=false;render()}}
const save=(r:any,name:string)=>localStorage.setItem("ic:reconnect",JSON.stringify({code:r.code,reconnectToken:r.reconnectToken,displayName:name}));
async function create(name:string,tut=false){tutorial={...tutorial,active:tut,firstRound:null};const r=await run(()=>t.createRoom(pid,name));if(!r.ok)return;if(r.code&&r.reconnectToken)save(r,name);if(tut){const s=await run(()=>t.start(),"Tutorial đã bắt đầu.");if(s.ok)screen="game"}else screen="lobby"}
async function join(code:string,name:string){tutorial={...tutorial,active:false,firstRound:null};const r=await run(()=>t.joinRoom(code,pid,name),"Đã tham gia phòng.");if(r.ok&&r.code&&r.reconnectToken){save(r,name);screen=t.room?.started?"game":"lobby"}}
async function recover(){const r=rec();if(!r)return;screen="recovery";const x=await run(()=>t.reconnectRoom(r.code,pid,r.reconnectToken),"Đã kết nối lại.");if(!x.ok)return;const s=await run(()=>t.getState());if(s.ok){t.applyState(s);screen=t.room?.started?"game":"lobby"}}
function seen(id:TutorialStepId){if(!tutorial.seenSteps.includes(id))tutorial.seenSteps.push(id);if(id==="T11")tutorial.completed=true;saveTutorial(localStorage,tutorial);render()}

const conn=()=>`<span class="connection ${t.connected?"online":"offline"}"><i></i>${t.connected?"Đã kết nối":"Mất kết nối"}</span>`;
const feedback=()=>`${busy?`<div class="toast">Đang xử lý…</div>`:""}${msg?`<div class="toast success">${e(msg)}</div>`:""}${err?`<div class="toast error">${e(err)}</div>`:""}`;
function landing(){const r=rec();return`<main class="landing-screen"><div class="ambient-stars"></div><div class="brand-lockup"><div class="sigil">IC</div><h1>INTERGENERATIONAL<br>CONTRACT</h1><p>Khế ước giữa các thế hệ</p><small>Một trò chơi của QuacQuaz</small></div><nav class="menu-card"><button data-screen="create">TẠO PHÒNG</button><button data-screen="join">THAM GIA PHÒNG</button><button data-screen="tutorial">HƯỚNG DẪN</button><button disabled>LUẬT CHƠI</button><button disabled>CÀI ĐẶT</button>${r?`<button id="recover">TIẾP TỤC PHÒNG ${e(r.code)}</button>`:""}</nav>${conn()}</main>`}
const nameField=()=>`<label class="field">Tên hiển thị<input id="name" maxlength="40" value="Người chơi"></label>`;
function entry(kind:"create"|"join"|"tutorial"){return`<main class="entry-screen"><button class="back" data-screen="landing">← TRỞ LẠI</button><section class="parchment form-card"><h1>${kind==="create"?"TẠO PHÒNG":kind==="join"?"THAM GIA PHÒNG":"HƯỚNG DẪN"}</h1>${nameField()}${kind==="join"?`<label class="field">Mã phòng<input id="code" maxlength="6" placeholder="ABC123"></label>`:""}<button id="entry-go" class="primary">${kind==="tutorial"?"BẮT ĐẦU TUTORIAL":kind==="join"?"THAM GIA":"TẠO PHÒNG"}</button></section>${conn()}</main>`}
function lobby(){const r=t.room;if(!r)return landing();const draw=(r.founderDraw||[]);return`<main class="lobby-screen"><header class="lobby-head"><div><small>MÃ PHÒNG</small><div class="room-pin">${e(r.code)}</div></div><div class="qr-placeholder" aria-label="QR chưa khả dụng"><span>QR</span><small>Đang chờ QR renderer</small></div>${conn()}</header><div class="lobby-layout"><section class="parchment roster"><h2>NGƯỜI THAM GIA · ${r.players.length}/30</h2>${r.players.map((p,i)=>`<div class="player-row tone-${i%5}"><b>${e(p.displayName)}</b><small>${p.host?"CHỦ PHÒNG":"HUMAN"}${p.connected?" · ONLINE":" · OFFLINE"}</small>${p.playerId===pid?"<em>BẠN</em>":""}</div>`).join("")}</section><aside class="parchment lobby-side"><h2>XÃ HỘI KHỞI ĐẦU</h2><p>${r.players.length<=10?`NPC sẽ tự bổ sung ${Math.max(0,10-r.players.length)} vị trí còn thiếu.`:"Máy chủ sẽ bốc thẻ Founder và chọn 10 Human sáng lập."}</p>${draw.length>10?`<div class="draw-note">Kết quả Founder sẽ dùng thứ hạng authoritative từ server.</div>`:""}${host()?`<button id="start" class="primary">BẮT ĐẦU GAME</button>`:"<p>Đang chờ chủ phòng bắt đầu…</p>"}</aside></div></main>`}

function hud(){const g=t.room?.game;if(!g)return"";return`<header class="world-hud" data-tutorial-zone="hud"><span><small>VÒNG</small><b>${g.round}</b></span><span><small>NĂM</small><b>${g.year}</b></span><span><small>DÂN SỐ</small><b>${g.population.total}</b></span><span><small>LẠM PHÁT</small><b>${pc(g.policy.inflationRate)}</b></span><span><small>NỢ CÔNG</small><b>${n(g.debt)} / ${n(g.government?.debtCeiling)}</b></span><span><small>SỰ KIỆN</small><b>—</b></span><span><small>${e(g.phase)}</small><b data-timer>${timer()}</b></span><button data-panel="chronicle">NIÊN SỬ</button><button data-help aria-label="Hướng dẫn">?</button></header>`}
function track(){const g=t.room?.game;const entries=(g?.turnOrder||[]).slice(0,6);return`<aside class="turn-track" data-tutorial-zone="turn-track"><h3>TURN TRACK</h3>${entries.map((x:any,i:number)=>{const owner=t.room?.players.find(p=>p.activeCharacterId===x.characterId);const local=x.characterId===t.player?.character?.id;return`<button class="turn-token ${x.characterId===g?.currentTurnCharacterId?"active":""} ${local?"local":""}" data-profile="${e(x.characterId)}"><span>${i+1}</span><b>${e(owner?.displayName||"Cư dân")}</b></button>`}).join("")||"<small>Chờ dữ liệu lượt</small>"}</aside>`}
function map(){return`<section class="world-map" style="--map-scale:${mapScale}" data-tutorial-zone="map"><div class="ambient-cloud c1"></div><div class="ambient-cloud c2"></div><div class="fog f1"></div><div class="fog f2"></div><button class="landmark gov" data-panel="government"><i>GOV</i>CHÍNH PHỦ</button><button class="landmark home" data-panel="residence"><i>HOME</i>KHU DÂN CƯ</button><div class="map-controls"><button data-panel="government">Government</button>${t.player?.queuePosition?"":`<button data-panel="residence">Home</button>`}<button data-zoom="in">+</button><button data-zoom="out">−</button></div></section>`}
function phase(){const g=t.room?.game,p=t.player;if(!g||g.ended||p?.queuePosition)return"";if(g.currentTurnPlayerId!==p?.playerId)return`<section class="phase-card"><small>ĐANG CHỜ LƯỢT</small><h2>${e(t.room?.players.find(x=>x.playerId===g.currentTurnPlayerId)?.displayName||"Cư dân")}</h2></section>`;if(g.phase==="mandatory")return`<section class="phase-card mandatory-card" data-tutorial-zone="mandatory"><small>PHASE BẮT BUỘC · PRESENTATION ONLY</small><h2>CHI PHÍ BẮT BUỘC</h2><div class="metrics"><span>Tài sản đầu vòng<b>${n(p.financial?.roundStartAssets)}</b></span><span>Thu nhập hộ<b>${n(p.financial?.householdNetIncome)}</b></span><span>Quota chung<b>${n(p.financial?.sharedQuotaCharge)}</b></span><span>Cash hiện tại<b>${n(p.financial?.cash)}</b></span></div><p>Không có nút bỏ qua. Kết quả thanh lý/phá sản chi tiết chỉ hiển thị khi server cung cấp dữ liệu tương ứng.</p></section>`;if(g.phase==="status")return`<section class="phase-card status-card" data-tutorial-zone="status"><small>ĐỊA VỊ · ${timer()}</small><h2>ĐỊA VỊ HIỆN TẠI: ${statusName(p.household?.status)}</h2><div class="status-context"><span>Tài sản đầu vòng <b>${n(p.financial?.roundStartAssets)}</b></span><span>Quyền truy cập <b>${e((p.financial?.resourceAccess||[]).join(" / "))}</b></span></div><div class="status-grid">${[["poor","BÌNH DÂN","Low"],["middle","TRUNG LƯU","Low + Mid"],["noble","QUÝ TỘC","Low + Mid + High"]].map(x=>`<button data-action='{"type":"status:set","status":"${x[0]}"}'><b>${x[1]}</b><small>Mở ${x[2]}</small></button>`).join("")}</div><p>Hiệu lực, phí, cạnh tranh/cap và refund do máy chủ xác nhận.</p></section>`;if(g.phase==="voluntary")return`<aside class="voluntary-dock" data-tutorial-zone="voluntary"><strong>${timer()}</strong>${[["market","THỊ TRƯỜNG"],["recovery","PHỤC HỒI"],["support","CHU CẤP"],["birth","SINH CON"],["marriage","HÔN NHÂN"]].map(x=>`<button data-panel="${x[0]}">${x[1]}</button>`).join("")}<button data-action='{"type":"turn:complete"}'>KẾT THÚC LƯỢT</button></aside>`;return""}
const close=()=>`<button class="panel-close" data-panel="overview" aria-label="Đóng">×</button>`;
function market(){const g=t.room?.game,p=t.player,access=p?.financial?.resourceAccess||["low"];let cards="";for(const type of["renewable","nonrenewable"] as const)for(const grade of["low","mid","high"] as const){const q=g?.market?.[type]?.[grade]||{},ok=access.includes(grade),empty=Number(q.pool)<=0;cards+=`<article class="resource-card ${ok?"":"locked"} ${empty?"empty":""}"><small>${type==="renewable"?"TÁI TẠO":"KHÔNG TÁI TẠO"}</small><h3>${grade.toUpperCase()}</h3><dl><dt>Giá</dt><dd>${n(q.price)}</dd><dt>Pool</dt><dd>${n(q.pool)}</dd><dt>Lợi suất</dt><dd>${pc(q.successReturn)}</dd><dt>Rủi ro</dt><dd>${pc(q.failureRate)}</dd><dt>Trợ giá</dt><dd>${pc(q.subsidyRate)}</dd></dl>${empty?`<b>HẾT NGUỒN CUNG</b>`:ok?`<button data-buy="${type}:${grade}">MUA</button>`:"<b>KHÓA THEO STATUS</b>"}</article>`}return`<section class="feature-sheet" data-tutorial-zone="market">${close()}<h2>THỊ TRƯỜNG</h2><div class="context-strip"><span>Cash ${n(p?.financial?.cash)}</span><span>Còn quota ${n(p?.financial?.spendingRemaining)}</span><span>Status ${statusName(p?.household?.status)}</span></div><div class="resource-grid">${cards}</div><label>Số đơn vị<input id="units" type="number" min="1" value="1"></label></section>`}
function recovery(){const g=t.room?.game,p=t.player;return`<section class="feature-sheet narrow" data-tutorial-zone="recovery">${close()}<h2>PHỤC HỒI TÀI NGUYÊN</h2><div class="context-strip"><span>Cash ${n(p?.financial?.cash)}</span><span>Còn quota ${n(p?.financial?.spendingRemaining)}</span></div>${["low","mid","high"].map(x=>`<button class="recovery-row" data-recover="${x}"><b>${x.toUpperCase()}</b><small>Pool tái tạo ${n(g?.market?.renewable?.[x]?.pool)}</small></button>`).join("")}<label>Số đơn vị<input id="recover-units" type="number" min="1" value="1"></label><p>Chi phí và pending vòng sau do server xác nhận khi gửi hành động.</p></section>`}
function support(){const a=t.player?.eligibleSupportTargets||[],p=t.player;return`<section class="feature-sheet narrow" data-tutorial-zone="support">${close()}<h2>CHU CẤP GIA ĐÌNH</h2><div class="context-strip"><span>Cash ${n(p?.financial?.cash)}</span><span>Còn quota ${n(p?.financial?.spendingRemaining)}</span></div>${a.length===0?"<p>Không có cha/mẹ hoặc con trực tiếp đủ điều kiện ở thời điểm hiện tại.</p>":`<label>Người nhận<select id="support-target">${a.map(x=>`<option value="${e(x.characterId)}">${e(`${x.relation==="parent"?"Cha/mẹ":"Con"} · ${x.ageLabel} · ${statusName(x.status)}`)}</option>`).join("")}</select></label><label>Số tiền<input id="amount" type="number" min="1" value="1"></label><button id="support-send">GỬI CHU CẤP</button>`}<p>Khoản bắt buộc đã được engine xử lý; đây là phần hỗ trợ tự nguyện thêm.</p></section>`}
function birth(){const p=t.player;return`<section class="feature-sheet narrow" data-tutorial-zone="birth">${close()}<h2>SINH CON</h2>${(p?.incomingBirthProposals||[]).map((x:any)=>`<article class="proposal"><div><b>Đề xuất sinh con #${e(x.index||"")}</b><small>Phản hồi cho proposal hiện tại</small></div><button data-action='{"type":"child:respond","proposalId":"${e(x.id)}","accept":true}'>ĐỒNG Ý</button><button data-action='{"type":"child:respond","proposalId":"${e(x.id)}","accept":false}'>TỪ CHỐI</button></article>`).join("")||"<p>Không có đề xuất đang chờ phản hồi.</p>"}${p?.canInitiateBirth?`<button data-action='{"type":"child:birth"}'>ĐỀ XUẤT SINH CON</button>`:"<p>Hiện chưa thể đề xuất sinh con theo trạng thái authoritative.</p>"}</section>`}
function marriage(){const p=t.player,g=t.room?.game,cid=p?.character?.id;const accepted=(g?.marriageProposals||[]).filter((x:any)=>x.status==="accepted"&&(x.proposerCharacterId===cid||x.targetCharacterId===cid));return`<section class="feature-sheet narrow" data-tutorial-zone="marriage">${close()}<h2>HÔN NHÂN</h2>${accepted.map((x:any)=>`<div class="notice accepted">Hôn nhân sẽ thực hiện cuối Vòng ${e(x.acceptedRound??g?.round??"")}</div>`).join("")}${(p?.incomingMarriageProposals||[]).map((x:any)=>`<article class="proposal"><div><b>Lời mời kết hôn</b><small>Đang chờ phản hồi</small></div><button data-panel="residence">ĐẾN NHÀ</button><button data-action='{"type":"marriage:respond","proposalId":"${e(x.id)}","accept":false}'>TỪ CHỐI</button><button data-action='{"type":"marriage:respond","proposalId":"${e(x.id)}","accept":true}'>ĐỒNG Ý</button></article>`).join("")||"<p>Không có lời mời đến.</p>"}<label>Gửi lời mời<select id="candidate"><option value="">Chọn người</option>${(p?.marriageCandidates||[]).map((x:any)=>`<option value="${e(x.characterId)}">${e(`${x.ageLabel} · ${statusName(x.status)}`)}</option>`).join("")}</select></label><button id="propose" ${p?.canSendMarriage?"":"disabled"}>GỬI LỜI MỜI KẾT HÔN</button></section>`}
function residence(){const g=t.room?.game,p=t.player;if(profileCharacterId){const c=g?.characters.find(x=>x.characterId===profileCharacterId);if(c)return`<section class="feature-sheet narrow residence-sheet">${close()}<button id="back-family">← GIA ĐÌNH</button><h2>HỒ SƠ NHÂN VẬT</h2><div class="portrait-placeholder">${e(c.ageStage)}</div><p>${e(c.ageLabel)}</p><p>Địa vị: ${statusName(c.status)}</p>${c.characterId===p?.character?.id?`<p>Cash hộ: ${n(p?.financial?.cash)}</p><p>Tài sản hộ: ${n(p?.financial?.householdAssets)}</p>`:"<p>Chỉ hiển thị thông tin công khai.</p>"}</section>`}const h=p?.household,ids=new Set<string>(h?.memberIds||[]),members=(g?.characters||[]).filter(c=>ids.has(c.characterId));return`<section class="feature-sheet narrow residence-sheet">${close()}<h2>GIA ĐÌNH</h2><div class="house-card"><strong>${statusName(h?.status)}</strong><span>Tài sản hộ ${n(p?.financial?.householdAssets)}</span><span>Cash ${n(p?.financial?.cash)}</span></div><h3>THÀNH VIÊN</h3>${members.map(c=>`<button class="member-row" data-profile="${e(c.characterId)}"><span>${e(c.ageLabel)}</span><b>${statusName(c.status)}</b></button>`).join("")||"<p>Không có dữ liệu thành viên.</p>"}</section>`}
function government(){const g=t.room?.game,gov=g?.government||{},ss=g?.socialSecurity||{};const tabs=`<nav class="drawer-tabs">${[["overview","TỔNG QUAN"],["budget","NGÂN SÁCH"],["debt","NỢ CÔNG"],["social","AN SINH"]].map(x=>`<button data-gov-tab="${x[0]}" class="${govTab===x[0]?"active":""}">${x[1]}</button>`).join("")}</nav>`;let body="";if(govTab==="overview")body=`<div class="metrics"><span>Ngân sách<b>${n(gov.budget)}</b></span><span>Dự trữ sàn<b>${n(gov.reserveFloor)}</b></span><span>Khủng hoảng tài khóa<b>${gov.fiscalCrisis?"CÓ":"KHÔNG"}</b></span></div>`;if(govTab==="budget")body=`<dl class="detail-list"><dt>Thuế vòng này</dt><dd>${n(gov.taxCollectedThisRound)}</dd><dt>Bảo trì</dt><dd>${n(gov.maintenancePaidThisRound)}</dd><dt>Trợ giá</dt><dd>${n(gov.subsidySpentThisRound)}</dd><dt>Vay mới</dt><dd>${n(gov.borrowedThisRound)}</dd></dl>`;if(govTab==="debt")body=`<div class="debt-meter"><b>${n(g?.debt)}</b><span>/ ${n(gov.debtCeiling)}</span></div><p>Đã trả vòng này: ${n(gov.debtRepaidThisRound)}</p>`;if(govTab==="social")body=`<dl class="detail-list"><dt>PAYG</dt><dd>${n(ss.payg)}</dd><dt>Support fund</dt><dd>${n(ss.support)}</dd><dt>Pension reserve</dt><dd>${n(ss.pensionReserve)}</dd><dt>Payout ratio</dt><dd>${pc(ss.pensionPayoutRatio)}</dd></dl>`;return`<section class="feature-sheet narrow government-sheet">${close()}<h2>CHÍNH PHỦ</h2>${tabs}${body}</section>`}
function chronicle(){const g=t.room?.game,p=t.player;return`<section class="feature-sheet history-sheet">${close()}<h2>NIÊN SỬ</h2><div class="chronicle-grid"><div><h3>HÀNH TRÌNH NGƯỜI CHƠI</h3><div class="journey-summary"><span>Kiếp sống ${n(p?.history?.lives)}</span><span>Đỉnh tài sản ${n(p?.history?.highestAssets)}</span><span>Địa vị cao nhất ${statusName(p?.history?.highestStatus)}</span></div>${(p?.history?.events||[]).slice(-30).reverse().map((x:any)=>`<p><b>V${x.round}</b> ${e(x.detail)}</p>`).join("")||"<p>Chưa có mốc lịch sử.</p>"}</div><div><h3>TỔNG QUAN THẾ GIỚI</h3>${(g?.historySnapshots||[]).slice(-8).reverse().map((x:any)=>`<div class="snapshot-row"><b>V${e(x.round??"")}</b><span>Dân số ${n(x.population??x.totalPopulation)}</span><span>Lạm phát ${pc(x.inflationRate)}</span></div>`).join("")}${(g?.chronology||[]).slice(-20).reverse().map(x=>`<p>${e(x)}</p>`).join("")}</div></div></section>`}
function panelView(){if(panel==="market")return market();if(panel==="recovery")return recovery();if(panel==="support")return support();if(panel==="birth")return birth();if(panel==="marriage")return marriage();if(panel==="chronicle")return chronicle();if(panel==="government")return government();if(panel==="residence")return residence();return""}
function queue(){return`<section class="queue-card parchment"><h1>HÀNG CHỜ TÁI SINH</h1><div class="queue-position">#${t.player?.queuePosition??"—"}</div><p>Bạn sẽ trở lại khi hệ thống tái sinh gán nhân vật mới. Không có thời gian chờ cố định và không có điều khiển gameplay trong trạng thái này.</p></section>`}
function founderBanner(){const draw=t.room?.founderDraw||[];if(founderBannerSeen||draw.length<=10||!t.room?.started)return"";window.setTimeout(()=>{founderBannerSeen=true;render()},2800);const founders=draw.filter(x=>x.founder).slice(0,10);return`<aside class="founder-banner"><b>FOUNDER DRAW</b><span>${founders.map(x=>e(x.displayName)).join(" · ")}</span><strong>XÃ HỘI ĐÃ ĐƯỢC THÀNH LẬP</strong></aside>`}
function roundTransition(){const g=t.room?.game;if(!transitionRound||!g)return"";return`<aside class="round-transition"><small>CHUYỂN VÒNG</small><b>VÒNG ${g.round} · NĂM ${g.year}</b><span>Dân số ${g.population.total} · Lạm phát ${pc(g.policy.inflationRate)}</span></aside>`}
function result(){const g=t.room?.game,rank=g?.rankings||[],winner=rank[0],extinction=/extinct|tuyệt chủng/i.test(g?.endingReason||"");let body="";if(resultTab==="ranking")body=`${!extinction&&winner?`<div class="winner-block"><small>NGƯỜI CHIẾN THẮNG</small><h2>${e(winner.playerId||"—")}</h2><b>${n(winner.averageAssets??winner.score??winner.cumulativeAssets)}</b></div>`:`<div class="failure-block"><h2>${e(g?.endingReason||"KẾT THÚC")}</h2><p>Không áp dụng winner presentation thông thường.</p></div>`}${rank.map((x:any,i:number)=>`<div class="rank-row"><b>#${i+1}</b><span>${e(x.playerId||"")}</span><strong>${n(x.averageAssets??x.score??x.cumulativeAssets)}</strong></div>`).join("")}`;if(resultTab==="journey")body=`<div class="result-scroll">${(t.player?.history?.events||[]).map((x:any)=>`<p><b>V${x.round}</b> ${e(x.detail)}</p>`).join("")||"<p>Không có dữ liệu hành trình.</p>"}</div>`;if(resultTab==="world")body=`<div class="result-scroll">${(g?.chronology||[]).slice().reverse().map(x=>`<p>${e(x)}</p>`).join("")}</div>`;return`<section class="end-screen"><div class="parchment end-card"><h1>BÁO CÁO KẾT THÚC</h1><nav class="result-tabs"><button data-result-tab="ranking" class="${resultTab==="ranking"?"active":""}">XẾP HẠNG</button><button data-result-tab="journey" class="${resultTab==="journey"?"active":""}">HÀNH TRÌNH</button><button data-result-tab="world" class="${resultTab==="world"?"active":""}">THẾ GIỚI</button></nav>${body}${host()?`<button id="replay">CHƠI LẠI</button>`:"<button disabled>CHƠI LẠI · CHỦ PHÒNG</button>"}</div></section>`}
const focusFor=(id:TutorialStepId|null)=>id==="T0"||id==="T10"?"hud":id==="T1"?"mandatory":id==="T2"?"status":id==="T3"?"voluntary":id==="T4"?"market":id==="T5"?"recovery":id==="T6"?"support":id==="T7"?"birth":id==="T8"?"marriage":id==="T9"?"queue":id==="T11"?"result":"";
function coach(){if(!tutorial.active)return"";const id=nextCoach(tutorial,t.room,t.player,panel);if(!id)return`<button class="tutorial-help" data-help>? HƯỚNG DẪN</button>`;const c=tutorialCopy[id];return`<aside class="coach" data-focus="${focusFor(id)}"><small>${id}</small><b>${c.title}</b><p>${c.body}</p><button data-seen="${id}">${id==="T0"?"BẮT ĐẦU":"ĐÃ HIỂU"}</button></aside>`}
function helpView(){if(!help||!tutorial.active)return"";const ids=unlockedSteps(tutorial,t.room,t.player,panel).filter(x=>tutorial.seenSteps.includes(x));return`<aside class="help-recap"><button data-help-close>×</button><h3>HƯỚNG DẪN ĐÃ MỞ</h3>${ids.map(id=>`<article><b>${id} · ${tutorialCopy[id].title}</b><p>${tutorialCopy[id].body}</p></article>`).join("")||"<p>Chưa có mục đã mở.</p>"}</aside>`}
function game(){const g=t.room?.game;if(!g)return lobby();if(tutorial.active&&tutorial.firstRound==null)tutorial.firstRound=g.round;const coachId=nextCoach(tutorial,t.room,t.player,panel);document.body.dataset.tutorialFocus=focusFor(coachId);if(g.ended)return hud()+result()+coach()+helpView();return hud()+`<main class="world-shell">${map()}${track()}${t.player?.queuePosition?queue():phase()}${panelView()}</main>`+founderBanner()+roundTransition()+coach()+helpView()}
function render(){app.innerHTML=(screen==="landing"?landing():screen==="create"?entry("create"):screen==="join"?entry("join"):screen==="tutorial"?entry("tutorial"):screen==="recovery"?`<main class="entry-screen"><section class="parchment"><h1>KHÔI PHỤC PHIÊN</h1><p>Đang kết nối lại…</p></section></main>`:screen==="lobby"?lobby():game())+feedback();bind()}
const v=(id:string)=>(document.querySelector<HTMLInputElement>(`#${id}`)?.value||"").trim();
function bind(){document.querySelectorAll<HTMLElement>("[data-screen]").forEach(x=>x.onclick=()=>{screen=x.dataset.screen as Screen;render()});document.querySelectorAll<HTMLElement>("[data-panel]").forEach(x=>x.onclick=()=>{panel=x.dataset.panel as Panel;if(panel!=="residence")profileCharacterId=null;render()});document.querySelectorAll<HTMLElement>("[data-profile]").forEach(x=>x.onclick=()=>{profileCharacterId=x.dataset.profile||null;panel="residence";render()});document.querySelectorAll<HTMLElement>("[data-seen]").forEach(x=>x.onclick=()=>seen(x.dataset.seen as TutorialStepId));document.querySelectorAll<HTMLElement>("[data-help]").forEach(x=>x.onclick=()=>{help=true;render()});document.querySelector<HTMLElement>("[data-help-close]")?.addEventListener("click",()=>{help=false;render()});document.querySelector<HTMLElement>("#back-family")?.addEventListener("click",()=>{profileCharacterId=null;render()});document.querySelectorAll<HTMLElement>("[data-gov-tab]").forEach(x=>x.onclick=()=>{govTab=x.dataset.govTab as typeof govTab;render()});document.querySelectorAll<HTMLElement>("[data-result-tab]").forEach(x=>x.onclick=()=>{resultTab=x.dataset.resultTab as typeof resultTab;render()});document.querySelectorAll<HTMLElement>("[data-zoom]").forEach(x=>x.onclick=()=>{mapScale=Math.max(.8,Math.min(1.35,mapScale+(x.dataset.zoom==="in"?.1:-.1)));render()});document.querySelector<HTMLElement>("#recover")?.addEventListener("click",recover);document.querySelector<HTMLElement>("#entry-go")?.addEventListener("click",()=>screen==="join"?join(v("code").toUpperCase(),v("name")):create(v("name"),screen==="tutorial"));document.querySelector<HTMLElement>("#start")?.addEventListener("click",()=>run(()=>t.start(),"Game đã bắt đầu."));document.querySelectorAll<HTMLElement>("[data-action]").forEach(x=>x.onclick=()=>run(()=>t.action(JSON.parse(x.dataset.action!)),"Đã gửi hành động."));document.querySelectorAll<HTMLElement>("[data-buy]").forEach(x=>x.onclick=()=>{const[a,b]=x.dataset.buy!.split(":"),action=marketAction(a,b,v("units"));run(()=>t.action(action),"Đã xử lý giao dịch.")});document.querySelectorAll<HTMLElement>("[data-recover]").forEach(x=>x.onclick=()=>{const action=recoveryAction(x.dataset.recover||"",v("recover-units"));run(()=>t.action(action),"Đã gửi phục hồi.")});document.querySelector<HTMLElement>("#support-send")?.addEventListener("click",()=>{const target=(document.querySelector<HTMLSelectElement>("#support-target")?.value||""),action=supportAction(target,v("amount"));run(()=>t.action(action),"Đã gửi chu cấp.")});document.querySelector<HTMLElement>("#propose")?.addEventListener("click",()=>{const target=(document.querySelector<HTMLSelectElement>("#candidate")?.value||""),action=marriageAction(target);run(()=>t.action(action),"Đã gửi lời mời.")});document.querySelector<HTMLElement>("#replay")?.addEventListener("click",()=>run(()=>t.replay(),"Đã đặt lại game."))}
render();
