import{GameTransport}from"./transport.js";import{loadTutorial,nextCoach,saveTutorial,tutorialCopy,unlockedSteps,type TutorialState}from"./tutorial.js";import type{Panel,Screen,TutorialStepId}from"./types.js";
const app=document.querySelector<HTMLElement>("#app")!,t=new GameTransport(),pid=localStorage.getItem("ic:playerId")||crypto.randomUUID();localStorage.setItem("ic:playerId",pid);let screen:Screen="landing",panel:Panel="overview",tutorial:TutorialState=loadTutorial(localStorage),help=false,busy=false,msg="",err="";t.onChange=()=>{if(t.room)screen=t.room.started?"game":"lobby";render()};t.onConnection=render;
const e=(x:any)=>String(x??"").replace(/[&<>\"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[c]!)),n=(x:any)=>Number.isFinite(Number(x))?Number(x).toLocaleString("vi-VN"):"—",pc=(x:any)=>Number.isFinite(Number(x))?`${(Number(x)*100).toFixed(1)}%`:"—";const rec=()=>{try{return JSON.parse(localStorage.getItem("ic:reconnect")||"null")}catch{return null}},host=()=>t.room?.hostPlayerId===pid;
function timer(){const a=t.room?.game?.phaseDeadlineAt;return a?`${Math.max(0,Math.ceil((a-Date.now())/1000))}s`:"—"}setInterval(()=>{const x=document.querySelector("[data-timer]");if(x)x.textContent=timer()},250);
async function run(op:()=>Promise<any>,ok=""){busy=true;msg=err="";render();try{const r=await op();if(!r.ok)err=r.error||"ACTION_FAILED";else msg=ok;return r}finally{busy=false;render()}}
const save=(r:any,name:string)=>localStorage.setItem("ic:reconnect",JSON.stringify({code:r.code,reconnectToken:r.reconnectToken,displayName:name}));
async function create(name:string,tut=false){tutorial={...tutorial,active:tut,firstRound:null};const r=await run(()=>t.createRoom(pid,name));if(!r.ok)return;if(r.code&&r.reconnectToken)save(r,name);if(tut){const s=await run(()=>t.start(),"Tutorial đã bắt đầu.");if(s.ok)screen="game"}else screen="lobby"}
async function join(code:string,name:string){tutorial={...tutorial,active:false,firstRound:null};const r=await run(()=>t.joinRoom(code,pid,name),"Đã tham gia phòng.");if(r.ok&&r.code&&r.reconnectToken){save(r,name);screen=t.room?.started?"game":"lobby"}}
async function recover(){const r=rec();if(!r)return;screen="recovery";const x=await run(()=>t.reconnectRoom(r.code,pid,r.reconnectToken),"Đã kết nối lại.");if(!x.ok)return;const s=await run(()=>t.getState());if(s.ok){t.applyState(s);screen=t.room?.started?"game":"lobby"}}
function seen(id:TutorialStepId){if(!tutorial.seenSteps.includes(id))tutorial.seenSteps.push(id);if(id==="T11")tutorial.completed=true;saveTutorial(localStorage,tutorial);render()}
const conn=()=>`<span class="connection ${t.connected?"online":"offline"}"><i></i>${t.connected?"Đã kết nối":"Mất kết nối"}</span>`,feedback=()=>`${busy?`<div class="toast">Đang xử lý…</div>`:""}${msg?`<div class="toast success">${e(msg)}</div>`:""}${err?`<div class="toast error">${e(err)}</div>`:""}`;
function landing(){const r=rec();return`<main class="landing-screen"><div class="brand-lockup"><div class="sigil">IC</div><h1>INTERGENERATIONAL<br>CONTRACT</h1><p>Khế ước giữa các thế hệ</p></div><nav class="menu-card"><button data-screen="create">TẠO PHÒNG</button><button data-screen="join">THAM GIA PHÒNG</button><button data-screen="tutorial">HƯỚNG DẪN</button><button disabled>LUẬT CHƠI</button><button disabled>CÀI ĐẶT</button>${r?`<button id="recover">TIẾP TỤC PHÒNG ${e(r.code)}</button>`:""}</nav>${conn()}</main>`}
const name=()=>`<label class="field">Tên hiển thị<input id="name" maxlength="40" value="Người chơi"></label>`;
function entry(kind:"create"|"join"|"tutorial"){return`<main class="entry-screen"><button class="back" data-screen="landing">← TRỞ LẠI</button><section class="parchment form-card"><h1>${kind==="create"?"TẠO PHÒNG":kind==="join"?"THAM GIA PHÒNG":"HƯỚNG DẪN"}</h1>${name()}${kind==="join"?`<label class="field">Mã phòng<input id="code" maxlength="6" placeholder="ABC123"></label>`:""}<button id="entry-go" class="primary">${kind==="tutorial"?"BẮT ĐẦU TUTORIAL":kind==="join"?"THAM GIA":"TẠO PHÒNG"}</button></section>${conn()}</main>`}
function lobby(){const r=t.room;if(!r)return landing();return`<main class="lobby-screen"><header><div><small>MÃ PHÒNG</small><div class="room-pin">${e(r.code)}</div></div>${conn()}</header><div class="lobby-layout"><section class="parchment roster"><h2>NGƯỜI THAM GIA · ${r.players.length}/30</h2>${r.players.map(p=>`<div class="player-row"><b>${e(p.displayName)}</b><small>${p.host?"CHỦ PHÒNG":"HUMAN"}${p.connected?" · ONLINE":" · OFFLINE"}</small>${p.playerId===pid?"<em>BẠN</em>":""}</div>`).join("")}</section><aside class="parchment"><h2>XÃ HỘI KHỞI ĐẦU</h2><p>${r.players.length<=10?`NPC sẽ tự bổ sung ${Math.max(0,10-r.players.length)} vị trí còn thiếu.`:"Máy chủ sẽ bốc thẻ Founder và chọn 10 Human sáng lập."}</p>${host()?`<button id="start" class="primary">BẮT ĐẦU GAME</button>`:"<p>Đang chờ chủ phòng bắt đầu…</p>"}</aside></div></main>`}
function hud(){const g=t.room?.game;if(!g)return"";return`<header class="world-hud">${[["VÒNG",g.round],["NĂM",g.year],["DÂN SỐ",g.population.total],["LẠM PHÁT",pc(g.policy.inflationRate)],["NỢ CÔNG",n(g.debt)]].map(x=>`<span><small>${x[0]}</small><b>${x[1]}</b></span>`).join("")}<span><small>${e(g.phase)}</small><b data-timer>${timer()}</b></span><button data-panel="chronicle">NIÊN SỬ</button><button data-help>?</button></header>`}
function track(){const g=t.room?.game;return`<aside class="turn-track"><h3>TURN TRACK</h3>${(g?.turnOrder||[]).slice(0,12).map((x:any,i:number)=>`<div class="turn-token ${x.characterId===g?.currentTurnCharacterId?"active":""}"><span>${i+1}</span><b>${e(t.room?.players.find(p=>p.activeCharacterId===x.characterId)?.displayName||"NPC")}</b></div>`).join("")||"<small>Chờ dữ liệu lượt</small>"}</aside>`}
function map(){return`<section class="world-map"><button class="landmark gov" data-panel="government"><i>GOV</i>CHÍNH PHỦ</button><button class="landmark home" data-panel="residence"><i>HOME</i>KHU DÂN CƯ</button></section>`}
function phase(){const g=t.room?.game,p=t.player;if(!g||g.ended||p?.queuePosition)return"";if(g.currentTurnPlayerId!==p?.playerId)return`<section class="phase-card"><small>ĐANG CHỜ LƯỢT</small><h2>${e(t.room?.players.find(x=>x.playerId===g.currentTurnPlayerId)?.displayName||"NPC")}</h2></section>`;if(g.phase==="mandatory")return`<section class="phase-card"><h2>CHI PHÍ BẮT BUỘC</h2><div class="metrics"><span>Cash <b>${n(p.financial?.cash)}</b></span><span>Tài sản hộ <b>${n(p.financial?.householdAssets)}</b></span><span>Quota đã tính <b>${n(p.financial?.sharedQuotaCharge)}</b></span></div><p>Chỉ trình bày; không thể bỏ qua.</p></section>`;if(g.phase==="status")return`<section class="phase-card"><h2>CHỌN ĐỊA VỊ</h2><div class="status-grid">${[["poor","BÌNH DÂN"],["middle","TRUNG LƯU"],["noble","QUÝ TỘC"]].map(x=>`<button data-action='{"type":"status:set","status":"${x[0]}"}'><b>${x[1]}</b></button>`).join("")}</div></section>`;if(g.phase==="voluntary")return`<aside class="voluntary-dock">${[["market","THỊ TRƯỜNG"],["recovery","PHỤC HỒI"],["support","HỖ TRỢ"],["birth","SINH CON"],["marriage","HÔN NHÂN"]].map(x=>`<button data-panel="${x[0]}">${x[1]}</button>`).join("")}<button data-action='{"type":"turn:complete"}'>KẾT THÚC LƯỢT</button></aside>`;return""}
const close=()=>`<button class="panel-close" data-panel="overview">×</button>`;
function market(){const g=t.room?.game,p=t.player,access=p?.financial?.resourceAccess||["low"];let cards="";for(const type of["renewable","nonrenewable"])for(const grade of["low","mid","high"]){const q=g?.market?.[type]?.[grade]||{},ok=access.includes(grade);cards+=`<article class="resource-card ${ok?"":"locked"}"><small>${type==="renewable"?"TÁI TẠO":"KHÔNG TÁI TẠO"}</small><h3>${grade.toUpperCase()}</h3><p>Giá ${n(q.price)} · Pool ${n(q.pool)}</p><p>Lợi suất ${pc(q.successReturn)} · Rủi ro ${pc(q.failureRate)}</p>${ok?`<button data-buy="${type}:${grade}">MUA</button>`:"<b>KHÓA THEO STATUS</b>"}</article>`}return`<section class="feature-sheet">${close()}<h2>THỊ TRƯỜNG</h2><div class="resource-grid">${cards}</div><label>Số đơn vị<input id="units" type="number" min="1" value="1"></label></section>`}
function support(){const a=t.player?.eligibleSupportTargets;return`<section class="feature-sheet narrow">${close()}<h2>HỖ TRỢ GIA ĐÌNH</h2>${a===undefined?`<div class="unavailable">Server chưa cung cấp danh sách người nhận đủ điều kiện. Client không yêu cầu nhập mã nội bộ và không tự suy diễn.</div>`:a.length===0?"<p>Không có mục tiêu hợp lệ.</p>":`<select id="support-target">${a.map(x=>`<option value="${e(x.characterId)}">${e(x.displayName||`${x.relation==="parent"?"Cha/mẹ":"Con"} · ${x.ageLabel||""}`)}</option>`).join("")}</select><input id="amount" type="number" min="1" value="1"><button id="support-send">GỬI HỖ TRỢ</button>`}</section>`}
function birth(){const p=t.player;return`<section class="feature-sheet narrow">${close()}<h2>SINH CON</h2>${(p?.incomingBirthProposals||[]).map((x:any)=>`<article class="proposal"><b>Đề xuất sinh con #${e(x.index||"")}</b><button data-action='{"type":"child:respond","proposalId":"${e(x.id)}","accept":true}'>ĐỒNG Ý</button><button data-action='{"type":"child:respond","proposalId":"${e(x.id)}","accept":false}'>TỪ CHỐI</button></article>`).join("")}${p?.canInitiateBirth?`<button data-action='{"type":"child:birth"}'>ĐỀ XUẤT SINH CON</button>`:"<p>Hiện chưa thể đề xuất sinh con.</p>"}</section>`}
function marriage(){const p=t.player;return`<section class="feature-sheet narrow">${close()}<h2>HÔN NHÂN</h2>${(p?.incomingMarriageProposals||[]).map((x:any)=>`<article class="proposal"><b>Lời mời đến</b><button data-action='{"type":"marriage:respond","proposalId":"${e(x.id)}","accept":true}'>ĐỒNG Ý</button><button data-action='{"type":"marriage:respond","proposalId":"${e(x.id)}","accept":false}'>TỪ CHỐI</button></article>`).join("")}<select id="candidate"><option value="">Chọn người</option>${(p?.marriageCandidates||[]).map((x:any)=>`<option value="${e(x.characterId)}">${e(x.ageLabel)} · ${e(x.status)}</option>`).join("")}</select><button id="propose" ${p?.canSendMarriage?"":"disabled"}>GỬI LỜI MỜI</button></section>`}
function panelView(){const g=t.room?.game;if(panel==="market")return market();if(panel==="recovery")return`<section class="feature-sheet narrow">${close()}<h2>PHỤC HỒI</h2>${["low","mid","high"].map(x=>`<button data-recover="${x}">${x.toUpperCase()} · Pool ${n(g?.market?.renewable?.[x]?.pool)}</button>`).join("")}<input id="recover-units" type="number" min="1" value="1"></section>`;if(panel==="support")return support();if(panel==="birth")return birth();if(panel==="marriage")return marriage();if(panel==="chronicle")return`<section class="feature-sheet">${close()}<h2>NIÊN SỬ</h2><div class="chronicle-grid"><div><h3>HÀNH TRÌNH</h3>${(t.player?.history?.events||[]).slice(-20).reverse().map((x:any)=>`<p><b>V${x.round}</b> ${e(x.detail)}</p>`).join("")}</div><div><h3>THẾ GIỚI</h3>${(g?.chronology||[]).slice(-25).reverse().map(x=>`<p>${e(x)}</p>`).join("")}</div></div></section>`;if(panel==="government")return`<section class="feature-sheet narrow">${close()}<h2>CHÍNH PHỦ</h2><p>Ngân sách ${n(g?.government?.budget)}</p><p>Trần nợ ${n(g?.government?.debtCeiling)}</p></section>`;if(panel==="residence")return`<section class="feature-sheet narrow">${close()}<h2>GIA ĐÌNH</h2><p>${e(t.player?.character?.ageLabel||"Không có nhân vật active")}</p><p>Cash hộ ${n(t.player?.financial?.cash)}</p><p>Tài sản hộ ${n(t.player?.financial?.householdAssets)}</p></section>`;return""}
function queue(){return`<section class="queue-card parchment"><h1>HÀNG CHỜ TÁI SINH</h1><div>#${t.player?.queuePosition??"—"}</div><p>Không có điều khiển hành động. Không có thời gian chờ cố định.</p></section>`}
function result(){const g=t.room?.game;return`<section class="end-screen"><div class="parchment end-card"><h1>${e(g?.endingReason||"KẾT THÚC")}</h1>${(g?.rankings||[]).map((x:any,i:number)=>`<div class="rank-row">#${i+1} · ${e(x.playerId||"")} · ${n(x.averageAssets??x.score??x.cumulativeAssets)}</div>`).join("")}${host()?`<button id="replay">CHƠI LẠI</button>`:"<button disabled>CHƠI LẠI · CHỦ PHÒNG</button>"}</div></section>`}
function coach(){if(!tutorial.active)return"";const id=nextCoach(tutorial,t.room,t.player,panel);if(!id)return`<button class="tutorial-help" data-help>? HƯỚNG DẪN</button>`;const c=tutorialCopy[id];return`<aside class="coach"><b>${id} · ${c.title}</b><p>${c.body}</p><button data-seen="${id}">${id==="T0"?"BẮT ĐẦU":"ĐÃ HIỂU"}</button></aside>`}
function helpView(){if(!help||!tutorial.active)return"";const ids=unlockedSteps(tutorial,t.room,t.player,panel).filter(x=>tutorial.seenSteps.includes(x));return`<aside class="help-recap"><button data-help-close>×</button>${ids.map(id=>`<article><b>${id} · ${tutorialCopy[id].title}</b><p>${tutorialCopy[id].body}</p></article>`).join("")}</aside>`}
function game(){const g=t.room?.game;if(!g)return lobby();if(tutorial.active&&tutorial.firstRound==null)tutorial.firstRound=g.round;if(g.ended)return hud()+result()+panelView()+coach()+helpView();return hud()+`<main class="world-shell">${map()}${track()}${t.player?.queuePosition?queue():phase()}${panelView()}</main>`+coach()+helpView()}
function render(){app.innerHTML=(screen==="landing"?landing():screen==="create"?entry("create"):screen==="join"?entry("join"):screen==="tutorial"?entry("tutorial"):screen==="recovery"?`<main class="entry-screen"><section class="parchment"><h1>KHÔI PHỤC PHIÊN</h1><p>Đang kết nối lại…</p></section></main>`:screen==="lobby"?lobby():game())+feedback();bind()}
const v=(id:string)=>(document.querySelector<HTMLInputElement>(`#${id}`)?.value||"").trim();function bind(){document.querySelectorAll<HTMLElement>("[data-screen]").forEach(x=>x.onclick=()=>{screen=x.dataset.screen as Screen;render()});document.querySelectorAll<HTMLElement>("[data-panel]").forEach(x=>x.onclick=()=>{panel=x.dataset.panel as Panel;render()});document.querySelectorAll<HTMLElement>("[data-seen]").forEach(x=>x.onclick=()=>seen(x.dataset.seen as TutorialStepId));document.querySelectorAll<HTMLElement>("[data-help]").forEach(x=>x.onclick=()=>{help=true;render()});document.querySelector<HTMLElement>("[data-help-close]")?.addEventListener("click",()=>{help=false;render()});document.querySelector<HTMLElement>("#recover")?.addEventListener("click",recover);document.querySelector<HTMLElement>("#entry-go")?.addEventListener("click",()=>screen==="join"?join(v("code").toUpperCase(),v("name")):create(v("name"),screen==="tutorial"));document.querySelector<HTMLElement>("#start")?.addEventListener("click",()=>run(()=>t.start(),"Game đã bắt đầu."));document.querySelectorAll<HTMLElement>("[data-action]").forEach(x=>x.onclick=()=>run(()=>t.action(JSON.parse(x.dataset.action!)),"Đã gửi hành động."));document.querySelectorAll<HTMLElement>("[data-buy]").forEach(x=>x.onclick=()=>{const[a,b]=x.dataset.buy!.split(":");run(()=>t.action({type:"resource:buy",resourceType:a,grade:b,units:Number(v("units"))}),"Đã xử lý giao dịch.")});document.querySelectorAll<HTMLElement>("[data-recover]").forEach(x=>x.onclick=()=>run(()=>t.action({type:"resource:recover",grade:x.dataset.recover,units:Number(v("recover-units"))}),"Đã gửi phục hồi."));document.querySelector<HTMLElement>("#support-send")?.addEventListener("click",()=>run(()=>t.action({type:"family:support",targetCharacterId:(document.querySelector<HTMLSelectElement>("#support-target")?.value||""),amount:Number(v("amount"))}),"Đã gửi hỗ trợ."));document.querySelector<HTMLElement>("#propose")?.addEventListener("click",()=>run(()=>t.action({type:"marriage:propose",targetCharacterId:(document.querySelector<HTMLSelectElement>("#candidate")?.value||"")}),"Đã gửi lời mời."));document.querySelector<HTMLElement>("#replay")?.addEventListener("click",()=>run(()=>t.replay(),"Đã đặt lại game."))}render();
