import type{BirthQuote,LifecycleResult,MarketQuote,PlayerSnapshot,RecoveryQuote,RoomSnapshot,StatusCardQuote,SupportTarget,WorldEventImpact,WorldEventOccurrence}from"./types.js";

type Detail={room:RoomSnapshot|null;player:PlayerSnapshot|null};
let latest:Detail={room:null,player:null};
let scheduled=false;
let chronicleFocus:string|null=null;
const esc=(x:any)=>String(x??"").replace(/[&<>\"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[c]!));
const vi=(x:any)=>Number.isFinite(Number(x))?Number(x).toLocaleString("vi-VN"):"—";
const pct=(x:any)=>Number.isFinite(Number(x))?`${(Number(x)*100).toFixed(1)}%`:"—";
const game=()=>latest.room?.game;
const player=()=>latest.player;
function schedule(){if(scheduled)return;scheduled=true;queueMicrotask(()=>{scheduled=false;decorate()})}
function charName(id:string){const c=game()?.characters.find(x=>x.characterId===id);const p=latest.room?.players.find(x=>x.activeCharacterId===id||x.aiTakeoverCharacterId===id||x.playerId===c?.ownerId);return p?.displayName||(c?.npc?"Cư dân NPC":"Cư dân")}
function reason(code:string|null|undefined){const map:Record<string,string>={
  MARKET_GRADE_LOCKED:"Cần Status phù hợp để mua cấp này.",MARKET_OUT_OF_SUPPLY:"Nguồn cung hiện đã hết.",MARKET_INSUFFICIENT_CASH:"Không đủ Cash.",MARKET_SPENDING_LIMIT_REACHED:"Đã chạm giới hạn chi tiêu tự nguyện.",
  RECOVERY_AT_CAPACITY:"Nguồn tái tạo đã đạt sức chứa khả dụng.",RECOVERY_INSUFFICIENT_CASH:"Không đủ Cash để phục hồi thêm.",RECOVERY_SPENDING_LIMIT_REACHED:"Đã chạm giới hạn chi tiêu tự nguyện.",
  SUPPORT_TARGET_INELIGIBLE:"Người này không còn đủ điều kiện nhận hỗ trợ.",SUPPORT_INSUFFICIENT_CASH:"Không đủ Cash để hỗ trợ.",SUPPORT_SPENDING_LIMIT_REACHED:"Đã chạm giới hạn chi tiêu tự nguyện.",SUPPORT_NO_ELIGIBLE_TARGETS:"Hiện không có cha/mẹ hoặc con trực tiếp đủ điều kiện.",
  BIRTH_NOT_VOLUNTARY:"Chỉ có thể đề xuất trong phase Tự nguyện.",BIRTH_NOT_CURRENT_TURN:"Chưa đến lượt của bạn.",BIRTH_REPRESENTATIVE_ONLY:"Chỉ người đại diện Household được đề xuất.",BIRTH_REQUIRES_COUPLE:"Cần Household có hai vợ/chồng hợp lệ.",BIRTH_WORKER_AGE_REQUIRED:"Cả hai vợ/chồng phải ở độ tuổi lao động.",BIRTH_PROPOSAL_LIMIT_REACHED:"Đã đạt giới hạn đề xuất sinh con của vòng này.",BIRTH_SLOT_ALREADY_USED:"Vị trí đề xuất này đã được sử dụng.",
  STATUS_INSUFFICIENT_CASH:"Không đủ Cash để mua địa vị này."
};return code?map[code]||"Hành động hiện không khả dụng theo trạng thái máy chủ.":""}
function ensureReason(root:HTMLElement,code:string|null|undefined){let p=root.querySelector<HTMLElement>(":scope > .authoritative-reason");if(!code){p?.remove();root.removeAttribute("data-unavailable");return}if(!p){p=document.createElement("p");p.className="authoritative-reason";root.appendChild(p)}p.textContent=reason(code);root.dataset.unavailable=code}

function statusCards(){const q=player()?.statusQuote;if(!q)return;document.querySelectorAll<HTMLElement>(".status-grid button[data-action]").forEach(btn=>{let st:string|null=null;try{st=JSON.parse(btn.dataset.action||"{}").status}catch{}const card=q.cards.find(x=>x.status===st) as StatusCardQuote|undefined;if(!card)return;btn.querySelector(".server-status-quote")?.remove();const line=document.createElement("span");line.className="server-status-quote";line.textContent=`Phí ${vi(card.fee)} · ${card.personsCharged} người`;btn.appendChild(line);btn.disabled=!!card.unavailableReason||!card.affordable;ensureReason(btn,card.unavailableReason)})}

function marketCards(){const quotes=player()?.marketQuotes||[];document.querySelectorAll<HTMLElement>('.feature-sheet[data-tutorial-zone="market"] .resource-card').forEach(card=>{const label=card.querySelector("small")?.textContent||"",grade=(card.querySelector("h3")?.textContent||"").toLowerCase(),type=label.includes("KHÔNG")?"nonrenewable":"renewable";const q=quotes.find(x=>x.resourceType===type&&x.grade===grade) as MarketQuote|undefined;if(!q)return;const controls=card.querySelector<HTMLElement>(".qty-controls"),input=controls?.querySelector<HTMLInputElement>('input[type="number"]'),max=controls?.querySelectorAll<HTMLButtonElement>("button")[3],submit=controls?.querySelector<HTMLButtonElement>("[data-submit]");if(!controls||!input||!max)return;const sig=`${q.purchasableMax}:${q.unavailableReason}`;if(controls.dataset.contractSig!==sig){controls.dataset.contractSig=sig;if(q.purchasableMax!=null){max.disabled=false;max.title=`Tối đa ${q.purchasableMax}`;input.max=String(q.purchasableMax);max.onclick=()=>input.value=String(q.purchasableMax);if(submit)submit.disabled=false}else{max.disabled=true;max.title=reason(q.unavailableReason);input.removeAttribute("max");if(submit)submit.disabled=true}ensureReason(card,q.unavailableReason)}})}

function recoveryCards(){const quotes=player()?.recoveryQuotes||[];document.querySelectorAll<HTMLElement>('.feature-sheet[data-tutorial-zone="recovery"] .recovery-card').forEach(card=>{const grade=(card.querySelector("h3")?.textContent||"").toLowerCase();const q=quotes.find(x=>x.grade===grade) as RecoveryQuote|undefined;if(!q)return;const controls=card.querySelector<HTMLElement>(".qty-controls"),input=controls?.querySelector<HTMLInputElement>('input[type="number"]'),buttons=controls?.querySelectorAll<HTMLButtonElement>("button"),max=buttons?.[2],submit=card.querySelector<HTMLButtonElement>(".recovery-row[data-recover]");if(!controls||!input||!max)return;const m=q.acceptedMax??null,sig=`${m}:${q.unavailableReason}`;if(controls.dataset.contractSig!==sig){controls.dataset.contractSig=sig;if(m!=null){max.disabled=false;max.title=`Tối đa ${m}`;input.max=String(m);max.onclick=()=>input.value=String(m);if(submit)submit.disabled=false}else{max.disabled=true;max.title=reason(q.unavailableReason);input.removeAttribute("max");if(submit)submit.disabled=true}ensureReason(card,q.unavailableReason)}})}

function supportCards(){const targets=player()?.eligibleSupportTargets||[];const cards=[...document.querySelectorAll<HTMLElement>('.feature-sheet[data-tutorial-zone="support"] .support-card')];cards.forEach((card,i)=>{const t=targets[i] as SupportTarget|undefined;if(!t)return;const controls=card.querySelector<HTMLElement>(".qty-controls"),input=controls?.querySelector<HTMLInputElement>('input[type="number"]'),buttons=controls?.querySelectorAll<HTMLButtonElement>("button"),max=buttons?.[2],send=card.querySelector<HTMLButtonElement>("[data-send]");if(!controls||!input||!max)return;const m=t.transferableMax??null,sig=`${m}:${t.unavailableReason}`;if(controls.dataset.contractSig!==sig){controls.dataset.contractSig=sig;if(m!=null){max.disabled=false;max.title=`Tối đa ${vi(m)}`;input.max=String(m);max.onclick=()=>input.value=String(m);if(send)send.disabled=false}else{max.disabled=true;max.title=reason(t.unavailableReason);input.removeAttribute("max");if(send)send.disabled=true}ensureReason(card,t.unavailableReason)}});const root=document.querySelector<HTMLElement>('.feature-sheet[data-tutorial-zone="support"]');if(root&&targets.length===0)ensureReason(root,player()?.supportUnavailableReason)}

function birthSlots(){const q=player()?.birthQuote as BirthQuote|null|undefined,root=document.querySelector<HTMLElement>('.feature-sheet[data-tutorial-zone="birth"]');if(!root||!q)return;let deck=root.querySelector<HTMLElement>(".birth-slot-deck");const sig=`${q.maxProposals}:${q.canInitiate}:${q.unavailableReason}:${q.slots.map(x=>`${x.index}-${x.status}-${x.available}-${x.unavailableReason}`).join("|")}`;if(!deck){deck=document.createElement("div");deck.className="birth-slot-deck";root.insertBefore(deck,root.children[2]||null)}if(deck.dataset.sig!==sig){deck.dataset.sig=sig;deck.innerHTML=q.slots.map(s=>`<article class="birth-slot ${s.available?"available":""}"><b>CON #${s.index}</b><span>${s.status==="available"?(s.available?"CÓ THỂ ĐỀ XUẤT":"CHƯA KHẢ DỤNG"):esc(String(s.status).toUpperCase())}</span>${s.unavailableReason?`<small>${esc(reason(s.unavailableReason))}</small>`:""}</article>`).join("")+`<p>${q.promotionalThirdSlot?"Sự kiện hiện cho phép vị trí #3.":`Giới hạn hiện tại: ${q.maxProposals} đề xuất.`}</p>`}const action=root.querySelector<HTMLButtonElement>('[data-action*="child:birth"]');if(action){action.disabled=!q.canInitiate;action.textContent=q.canInitiate?"ĐỀ XUẤT SINH CON TIẾP THEO":"ĐỀ XUẤT SINH CON";action.title=q.unavailableReason?reason(q.unavailableReason):""}ensureReason(root,q.unavailableReason)}

function voluntaryAvailability(){const dock=document.querySelector<HTMLElement>(".approved-voluntary");if(!dock)return;const p=player();const summary:[string,string|null|undefined][]=[
  ["market",p?.marketQuotes?.length&&p.marketQuotes.every(q=>q.purchasableMax==null)?p.marketQuotes[0]?.unavailableReason:null],
  ["recovery",p?.recoveryQuotes?.length&&p.recoveryQuotes.every(q=>q.acceptedMax==null)?p.recoveryQuotes[0]?.unavailableReason:null],
  ["support",p?.eligibleSupportTargets.length===0?p.supportUnavailableReason:null],
  ["birth",p?.birthQuote&&!p.birthQuote.canInitiate?p.birthQuote.unavailableReason:null]
];for(const [panel,code]of summary){const b=dock.querySelector<HTMLElement>(`[data-panel="${panel}"]`);if(!b)continue;b.classList.toggle("server-unavailable",!!code);b.title=code?reason(code):""}}

function lifecycleText(r:LifecycleResult){if(r.type==="elderly_medical")return`Y TẾ CAO TUỔI · ĐÃ TRẢ ${vi(r.medicalPaid)} / ${vi(r.medicalDue)}`;if(r.type==="death")return`${r.joint?"HAI VỢ CHỒNG TỬ VONG":"TỬ VONG"} · Vòng ${r.round}`;if(r.type==="inheritance"){const heir=r.beneficiaries.map(x=>`${charName(x.characterId)} nhận ${vi(x.amount)}`).join(" · ");return`DI SẢN ${vi(r.estateTotal)}${heir?` · ${heir}`:""}${r.governmentTransfer>0?` · Chuyển Chính phủ ${vi(r.governmentTransfer)}`:""}`}if(r.type==="queue_entry")return`VÀO HÀNG CHỜ${r.queuePosition?` · #${r.queuePosition}`:""}${r.assignmentReason?` · ${r.assignmentReason==="bankruptcy"?"PHÁ SẢN":"TỬ VONG"}`:""}`;return`KIẾP SỐNG MỚI ĐÃ ĐƯỢC GÁN${r.assignmentReason?` · ${r.assignmentReason==="birth"?"TRẺ MỚI SINH":r.assignmentReason==="bankruptcy"?"SAU PHÁ SẢN":"SAU TỬ VONG"}`:""}`}
function lifecycle(){const rows=player()?.recentLifecycleResults||[];const queue=document.querySelector<HTMLElement>(".queue-card"),host=queue||document.querySelector<HTMLElement>(".world-map");if(!host||!rows.length)return;const relevant=rows.slice(-4).reverse(),sig=relevant.map(x=>x.id).join("|");let box=host.querySelector<HTMLElement>(":scope > .lifecycle-result-stack");if(!box){box=document.createElement("aside");box.className="lifecycle-result-stack";host.appendChild(box)}if(box.dataset.sig!==sig){box.dataset.sig=sig;box.innerHTML=relevant.map(r=>`<article class="lifecycle-${r.type}"><small>V${r.round} · Năm ${r.year}</small><b>${esc(lifecycleText(r))}</b></article>`).join("")}}

const impactLabels:Record<string,string>={EVENT_RENEWABLE_POOL:"Pool tái tạo",EVENT_NONRENEWABLE_POOL:"Pool không tái tạo",EVENT_MARKET_RETURN_DELTA:"Lợi suất thị trường",EVENT_SUPPORT_FUND_INJECTION:"Quỹ hỗ trợ",EVENT_BIRTH_PROPOSAL_LIMIT:"Giới hạn đề xuất sinh con",EVENT_DEBT_INTEREST_MULTIPLIER:"Hệ số lãi nợ công",EVENT_RECOVERY_COST_MULTIPLIER:"Hệ số chi phí phục hồi",EVENT_MARKET_MIN_PRICE:"Giá thị trường tối thiểu",EVENT_MARKET_MAX_PRICE:"Giá thị trường tối đa",EVENT_MANDATORY_MEDICAL_PER_CHARACTER:"Phí y tế bắt buộc / người"};
function impactValue(x:WorldEventImpact){const v=x.unit==="ratio"?pct(x.value):vi(x.value),d=x.delta==null?"":` (${x.delta>=0?"+":""}${x.unit==="ratio"?pct(x.delta):vi(x.delta)})`;return`${v}${d}`}
function eventCard(event:WorldEventOccurrence){return`<article class="structured-world-event" data-world-event-id="${esc(event.id)}"><header><small>V${event.round} · Năm ${event.year}</small><h3>${esc(event.name)}</h3></header>${event.impacts.map(x=>`<p><span>${esc(impactLabels[x.labelKey]||x.system)}</span><b>${esc(impactValue(x))}</b></p>`).join("")||"<p>Không có hệ thống nào bị thay đổi số liệu trong sự kiện này.</p>"}</article>`}
function worldEvent(){const e=game()?.worldEvent,banner=document.querySelector<HTMLElement>(".world-event-banner");if(!e||!banner)return;let btn=banner.querySelector<HTMLButtonElement>(".event-detail-open");if(!btn){btn=document.createElement("button");btn.className="event-detail-open";btn.textContent="CHI TIẾT";banner.appendChild(btn)}btn.onclick=()=>{let panel=document.querySelector<HTMLElement>(".world-event-detail-panel");if(!panel){panel=document.createElement("section");panel.className="world-event-detail-panel feature-sheet narrow";document.body.appendChild(panel)}panel.innerHTML=`<button class="panel-close" data-close-event>×</button>${eventCard(e)}<button data-event-chronicle>XEM TRONG NIÊN SỬ</button>`;panel.querySelector<HTMLElement>("[data-close-event]")!.onclick=()=>panel?.remove();panel.querySelector<HTMLElement>("[data-event-chronicle]")!.onclick=()=>{chronicleFocus=e.chronicleEntryId;panel?.remove();(document.querySelector<HTMLElement>('[data-panel="chronicle"]'))?.click();schedule()}}}
function chronicleEvents(){const sheet=document.querySelector<HTMLElement>(".history-sheet"),events=game()?.worldEventOccurrences||[];if(!sheet)return;let box=sheet.querySelector<HTMLElement>(".structured-world-events");if(!box){box=document.createElement("section");box.className="structured-world-events";box.innerHTML="<h3>SỰ KIỆN THẾ GIỚI</h3><div></div>";sheet.appendChild(box)}const list=box.querySelector<HTMLElement>("div")!,sig=events.map(x=>x.id).join("|");if(list.dataset.sig!==sig){list.dataset.sig=sig;list.innerHTML=events.slice(-20).reverse().map(eventCard).join("")||"<p>Chưa có sự kiện thế giới.</p>"}list.querySelectorAll<HTMLElement>("[data-world-event-id]").forEach(x=>x.classList.toggle("focused-event",!!chronicleFocus&&x.dataset.worldEventId===chronicleFocus));if(chronicleFocus){const target=list.querySelector<HTMLElement>(`[data-world-event-id="${CSS.escape(chronicleFocus)}"]`);target?.scrollIntoView({block:"center"});chronicleFocus=null}}

function immigrationAndTakeover(){const g=game();if(!g)return;const arrivals=Object.values(g.residenceDirectory||{}).filter(r=>r.origin==="immigrant"&&r.createdRound===g.round&&r.activeOnMap);for(const r of arrivals)document.querySelector<HTMLElement>(`.residence-map-marker[data-residence-id="${CSS.escape(r.residenceId)}"]`)?.classList.add("immigrant-arrival");let badge=document.querySelector<HTMLElement>(".immigration-arrival-notice");if(arrivals.length){if(!badge){badge=document.createElement("aside");badge.className="immigration-arrival-notice";document.querySelector(".world-map")?.appendChild(badge)}badge.textContent=`${arrivals.length} NGƯỜI NHẬP CƯ MỚI · RESIDENCE MỚI ĐÃ XUẤT HIỆN`}else badge?.remove();const me=latest.room?.players.find(x=>x.playerId===player()?.playerId),old=me?.aiTakeoverCharacterId?g.characters.find(x=>x.characterId===me.aiTakeoverCharacterId):null;if(me?.queuePosition&&old?.currentResidenceId){const marker=document.querySelector<HTMLElement>(`.residence-map-marker[data-residence-id="${CSS.escape(old.currentResidenceId)}"]`);marker?.classList.add("former-character-home");marker?.setAttribute("title","Nhân vật cũ hiện do NPC điều khiển")}}

function marriageResidenceLinks(){const g=game(),cid=player()?.character?.id,map=document.querySelector<HTMLElement>(".world-map");if(!g||!cid||!map)return;let svg=map.querySelector<SVGSVGElement>("svg.marriage-residence-links");if(!svg){svg=document.createElementNS("http://www.w3.org/2000/svg","svg");svg.setAttribute("class","marriage-residence-links");svg.setAttribute("viewBox","0 0 100 100");svg.setAttribute("preserveAspectRatio","none");map.appendChild(svg)}const accepted=(g.marriageProposals||[]).filter((p:any)=>p.status==="accepted"&&(p.proposerCharacterId===cid||p.targetCharacterId===cid));const lines=accepted.map((p:any)=>{const a=g.characters.find(x=>x.characterId===p.proposerCharacterId),b=g.characters.find(x=>x.characterId===p.targetCharacterId),ra=a?.currentResidenceId?g.residenceDirectory?.[a.currentResidenceId]:null,rb=b?.currentResidenceId?g.residenceDirectory?.[b.currentResidenceId]:null;if(!ra||!rb||!ra.activeOnMap||!rb.activeOnMap)return"";return`<line x1="${ra.coordinates.x*100}" y1="${ra.coordinates.y*100}" x2="${rb.coordinates.x*100}" y2="${rb.coordinates.y*100}"/>`}).join("");if(svg.dataset.sig!==lines){svg.dataset.sig=lines;svg.innerHTML=lines}const panel=document.querySelector<HTMLElement>('.feature-sheet[data-tutorial-zone="marriage"]');if(panel){const proposals=player()?.incomingMarriageProposals||[];[...panel.querySelectorAll<HTMLButtonElement>(".proposal [data-panel=\"residence\"]")].forEach((b,i)=>{const p=proposals[i],other=p?g.characters.find(x=>x.characterId===p.proposerCharacterId):null;b.onclick=ev=>{ev.preventDefault();ev.stopPropagation();const rid=other?.currentResidenceId;if(!rid)return;document.querySelector<HTMLElement>(`.residence-map-marker[data-residence-id="${CSS.escape(rid)}"]`)?.click()}})}}

function decorate(){statusCards();marketCards();recoveryCards();supportCards();birthSlots();voluntaryAvailability();lifecycle();worldEvent();chronicleEvents();immigrationAndTakeover();marriageResidenceLinks()}
window.addEventListener("ic:snapshot",ev=>{latest=(ev as CustomEvent<Detail>).detail;schedule()});
new MutationObserver(schedule).observe(document.body,{childList:true,subtree:true});
schedule();
