export interface UiArtManifest{version:number;tileSize:number;iconSize:number;portraitSize:number;assets:Record<string,string>}
export const UI_ART_ROOT="./public/assets/ui/v1/";
export const UI_ART_MANIFEST=`${UI_ART_ROOT}manifest.json`;

export function portraitKey(characterId:string){let h=0;for(const ch of characterId)h=(h*31+ch.charCodeAt(0))>>>0;return`portraitBase${String(h%8+1).padStart(2,"0")}`}
export function assetUrl(manifest:UiArtManifest,key:string){const path=manifest.assets[key];return path?`${UI_ART_ROOT}${path}`:null}
export function dataAttr(key:string){return`data-ui-${key.replace(/[A-Z]/g,m=>`-${m.toLowerCase()}`)}`}

let currentManifest:UiArtManifest|null=null;
let selectedProfileId="";

function probe(url:string){return new Promise<boolean>(resolve=>{const img=new Image();img.onload=()=>resolve(true);img.onerror=()=>resolve(false);img.src=url})}
function cssName(key:string){return`--ui-${key.replace(/[A-Z]/g,m=>`-${m.toLowerCase()}`)}`}
function ready(key:string){return document.documentElement.getAttribute(dataAttr(key))==="ready"}
function cssVar(key:string){return`var(${cssName(key)})`}

function installAssetRules(){if(document.getElementById("ui-art-v1-rules"))return;const style=document.createElement("style");style.id="ui-art-v1-rules";style.textContent=`
:root{--ui-art-version:1}.world-map,.landmark,.parchment,.feature-sheet,.portrait-placeholder,.ui-icon-art,.terrain-raster-layer,.terrain-raster-layer i,.ui-ambience-art{image-rendering:pixelated}
html[data-ui-terrain-atlas="ready"] .world-map{background:#31523a}.terrain-raster-layer{position:absolute;inset:0;z-index:0;display:grid;grid-template-columns:repeat(30,64px);grid-auto-rows:64px;overflow:hidden;pointer-events:none;transform:scale(var(--map-scale));transform-origin:center}.terrain-raster-layer i{width:64px;height:64px;background-image:var(--ui-terrain-atlas);background-size:512px 512px;background-repeat:no-repeat}
html[data-ui-government="ready"] .landmark.gov{background-image:var(--ui-government);background-size:contain;background-repeat:no-repeat;background-position:center;background-color:transparent;color:transparent;border-color:transparent;box-shadow:none;min-width:160px;min-height:160px}
html[data-ui-residence-middle="ready"] .landmark.home{background-image:var(--ui-residence-middle);background-size:contain;background-repeat:no-repeat;background-position:center;background-color:transparent;color:transparent;border-color:transparent;box-shadow:none;min-width:96px;min-height:96px}
html[data-ui-local-status="poor"][data-ui-residence-poor="ready"] .landmark.home{background-image:var(--ui-residence-poor)}html[data-ui-local-status="noble"][data-ui-residence-noble="ready"] .landmark.home{background-image:var(--ui-residence-noble)}
html[data-ui-local-marker="ready"] .landmark.home:after{content:"";position:absolute;width:24px;height:24px;left:50%;top:-8px;transform:translateX(-50%);background:var(--ui-local-marker) center/24px 24px no-repeat;image-rendering:pixelated}
html[data-ui-parchment-panel="ready"] .parchment,html[data-ui-parchment-panel="ready"] .feature-sheet{border-image:var(--ui-parchment-panel) 24 fill / 24px / 0 stretch;background:none}
html[data-ui-wood-panel="ready"] .phase-card,html[data-ui-wood-panel="ready"] .turn-track,html[data-ui-wood-panel="ready"] .voluntary-dock{border-image:var(--ui-wood-panel) 24 fill / 24px / 0 stretch;background:none}
html[data-ui-dark-panel="ready"] .end-card,html[data-ui-dark-panel="ready"] .help-recap{border-image:var(--ui-dark-panel) 24 fill / 24px / 0 stretch;background:none}
html[data-ui-button-primary="ready"] button.primary{border-image:var(--ui-button-primary) 20 fill / 20px / 0 stretch;background:none}
html[data-ui-button-secondary="ready"] button:not(.primary):not(:disabled){border-image:var(--ui-button-secondary) 20 fill / 20px / 0 stretch}
html[data-ui-button-danger="ready"] .proposal button[data-action*='false']{border-image:var(--ui-button-danger) 20 fill / 20px / 0 stretch}
html[data-ui-tab-active="ready"] .drawer-tabs .active,html[data-ui-tab-active="ready"] .result-tabs .active{border-image:var(--ui-tab-active) 20 fill / 20px / 0 stretch}html[data-ui-tab-idle="ready"] .drawer-tabs button:not(.active),html[data-ui-tab-idle="ready"] .result-tabs button:not(.active){border-image:var(--ui-tab-idle) 20 fill / 20px / 0 stretch}
html[data-ui-cloud01="ready"] .ambient-cloud.c1{background-image:var(--ui-cloud01);background-size:contain;background-repeat:no-repeat;background-color:transparent}html[data-ui-cloud02="ready"] .ambient-cloud.c2{background-image:var(--ui-cloud02);background-size:contain;background-repeat:no-repeat;background-color:transparent}html[data-ui-fog-edge="ready"] .fog{background-image:var(--ui-fog-edge);background-size:cover;background-repeat:no-repeat;background-color:transparent}
.ui-icon-art{display:inline-block;width:24px;height:24px;flex:0 0 24px;background-position:center;background-repeat:no-repeat;background-size:24px 24px;vertical-align:middle;margin-right:.35rem}.world-hud>span>.ui-icon-art{position:absolute;margin-left:54px;margin-top:4px;opacity:.8}.world-hud>span{position:relative}.landmark i{display:none}.portrait-placeholder[data-ui-portrait]{background-position:center;background-repeat:no-repeat;background-size:96px 96px;width:96px;height:96px;color:transparent;border:0}
.ui-ambience-art{position:absolute;z-index:2;pointer-events:none;background-position:center;background-repeat:no-repeat;background-size:contain;opacity:.6}.ui-bird{width:48px;height:48px;left:68%;top:12%;background-image:var(--ui-bird01)}.ui-smoke{width:64px;height:64px;left:55%;top:31%;background-image:var(--ui-smoke01);opacity:.35}.ui-ripple{width:64px;height:32px;left:20%;top:62%;background-image:var(--ui-water-ripple01);opacity:.5}
html[data-ui-founder-seal="ready"] .founder-banner:before{content:"";display:block;width:64px;height:64px;margin:auto;background:var(--ui-founder-seal) center/64px 64px no-repeat;image-rendering:pixelated}html[data-ui-round-divider="ready"] .round-transition:before{content:"";display:block;width:128px;height:32px;margin:auto;background:var(--ui-round-divider) center/contain no-repeat;image-rendering:pixelated}html[data-ui-extinction-mark="ready"] .failure-block[data-extinction="1"]:before{content:"";display:block;width:96px;height:96px;margin:auto;background:var(--ui-extinction-mark) center/96px 96px no-repeat;image-rendering:pixelated}
`;document.head.appendChild(style)}

const hudIcons:Record<string,string>={"VÒNG":"iconRound","NĂM":"iconYear","DÂN SỐ":"iconPopulation","LẠM PHÁT":"iconInflation","NỢ CÔNG":"iconDebt","SỰ KIỆN":"iconEvent"};
const panelIcons:Record<string,string>={market:"iconMarket",recovery:"iconRecovery",support:"iconSupport",birth:"iconBirth",marriage:"iconMarriage",chronicle:"iconChronicle",government:"iconGovernment",residence:"iconHome"};
const actionIcons:Record<string,string>={"turn:complete":"iconEndTurn","child:birth":"iconBirth","marriage:respond":"iconMarriage","child:respond":"iconBirth"};
function addIcon(el:Element,key:string){if(!ready(key)||el.querySelector(":scope > .ui-icon-art"))return;const i=document.createElement("span");i.className="ui-icon-art";i.setAttribute("aria-hidden","true");i.style.backgroundImage=cssVar(key);el.prepend(i)}
function detectLocalStatus(){const texts=[document.querySelector(".status-card h2")?.textContent,document.querySelector(".house-card strong")?.textContent,...Array.from(document.querySelectorAll(".context-strip span")).map(x=>x.textContent)].filter(Boolean).join(" ").toLowerCase();if(texts.includes("quý tộc"))document.documentElement.dataset.uiLocalStatus="noble";else if(texts.includes("trung lưu"))document.documentElement.dataset.uiLocalStatus="middle";else if(texts.includes("bình dân"))document.documentElement.dataset.uiLocalStatus="poor"}
function decorateTerrain(){const map=document.querySelector<HTMLElement>(".world-map");if(!map||!ready("terrainAtlas")||map.querySelector(".terrain-raster-layer"))return;const layer=document.createElement("div");layer.className="terrain-raster-layer";const coords=[[0,0],[1,0],[2,0],[0,1],[1,1],[3,0],[4,0],[0,3],[1,3],[2,3],[3,3]];for(let i=0;i<600;i++){const tile=document.createElement("i");const c=coords[(i*7+Math.floor(i/30)*3)%coords.length];tile.style.backgroundPosition=`-${c[0]*64}px -${c[1]*64}px`;layer.appendChild(tile)}map.prepend(layer)}
function decoratePortrait(){const p=document.querySelector<HTMLElement>(".portrait-placeholder");if(!p||!currentManifest)return;const key=portraitKey(selectedProfileId||p.textContent||"resident");if(!ready(key))return;p.dataset.uiPortrait=key;p.style.backgroundImage=cssVar(key)}
function decorateAmbience(){const map=document.querySelector<HTMLElement>(".world-map");if(!map)return;for(const [key,cls] of [["bird01","ui-bird"],["smoke01","ui-smoke"],["waterRipple01","ui-ripple"]] as const){if(!ready(key)||map.querySelector(`.${cls}`))continue;const x=document.createElement("span");x.className=`ui-ambience-art ${cls}`;map.appendChild(x)}}
function decorateIcons(){document.querySelectorAll(".world-hud>span").forEach(x=>{const k=hudIcons[x.querySelector("small")?.textContent?.trim()||""];if(k)addIcon(x,k)});document.querySelectorAll<HTMLElement>("[data-panel]").forEach(x=>{const k=panelIcons[x.dataset.panel||""];if(k)addIcon(x,k)});document.querySelectorAll<HTMLElement>("[data-zoom]").forEach(x=>addIcon(x,x.dataset.zoom==="in"?"iconZoomIn":"iconZoomOut"));document.querySelectorAll<HTMLElement>("[data-action]").forEach(x=>{try{const a=JSON.parse(x.dataset.action||"{}");const k=actionIcons[a.type];if(k)addIcon(x,k);if(a.accept===true)addIcon(x,"iconAccept");if(a.accept===false)addIcon(x,"iconReject")}catch{}});document.querySelectorAll<HTMLElement>(".panel-close").forEach(x=>addIcon(x,"iconClose"));document.querySelectorAll<HTMLElement>("#recover").forEach(x=>addIcon(x,"iconReconnect"));document.querySelectorAll<HTMLElement>(".queue-card h1").forEach(x=>addIcon(x,"iconQueue"))}
function decorateTransitions(){const f=document.querySelector<HTMLElement>(".failure-block");if(f&&/extinct|tuyệt chủng/i.test(f.textContent||""))f.dataset.extinction="1"}
function decorateDom(){if(!currentManifest)return;detectLocalStatus();decorateTerrain();decoratePortrait();decorateAmbience();decorateIcons();decorateTransitions()}

export async function initUiArt(){installAssetRules();let manifest:UiArtManifest;try{const r=await fetch(UI_ART_MANIFEST,{cache:"no-cache"});if(!r.ok)throw new Error(String(r.status));manifest=await r.json()}catch{document.documentElement.dataset.uiArt="fallback";return{manifest:null,loaded:[] as string[]}}
 const loaded:string[]=[];await Promise.all(Object.keys(manifest.assets).map(async key=>{const url=assetUrl(manifest,key);if(!url)return;if(await probe(url)){loaded.push(key);document.documentElement.style.setProperty(cssName(key),`url("${url}")`);document.documentElement.setAttribute(dataAttr(key),"ready")}}));currentManifest=manifest;document.documentElement.dataset.uiArt=loaded.length===Object.keys(manifest.assets).length?"ready":loaded.length?"partial":"fallback";decorateDom();return{manifest,loaded}}

if(typeof window!=="undefined"&&typeof document!=="undefined"){
 document.addEventListener("click",e=>{const p=(e.target as Element|null)?.closest?.("[data-profile]") as HTMLElement|null;if(p?.dataset.profile)selectedProfileId=p.dataset.profile;queueMicrotask(decorateDom)});
 new MutationObserver(()=>queueMicrotask(decorateDom)).observe(document.body,{childList:true,subtree:true});
 void initUiArt();
}
