import { GameEngine } from "./engine.js";
import { ResourceGrade,ResourceType } from "./config.js";
export function governmentReserveFloor(game:GameEngine){return game.cfg.government.maintenanceBase*game.state.priceIndex*game.cfg.government.reserveRounds}
function spendable(game:GameEngine){return Math.max(0,game.state.government.budget-game.state.government.reserveFloor)}
function record(game:GameEngine,type:string,amount:number,detail:string){const g=game.state.government;g.interventions.push(detail);g.interventionLedger.push({type,amount,detail})}
function spend(game:GameEngine,type:string,amount:number,detail:string,allowReserve=false){const g=game.state.government;if(g.fiscalCrisis&&!['maintenance','social_fund','debt_interest'].includes(type))return 0;const cap=allowReserve?g.budget:spendable(game);const actual=Math.min(Math.max(0,amount),cap);if(actual<=0)return 0;g.budget-=actual;g.spendingThisRound+=actual;record(game,type,actual,detail.replace('{amount}',actual.toFixed(2)));return actual}
export function maintainGovernment(game:GameEngine){const g=game.state.government;const maintenance=game.cfg.government.maintenanceBase*game.state.priceIndex;g.reserveFloor=governmentReserveFloor(game);const required=maintenance+g.reserveFloor;if(g.budget<required)game.borrowGovernment(required-g.budget,'bảo đảm vận hành và dự phòng');const paid=spend(game,'maintenance',maintenance,'Chi duy trì Nhà nước {amount}',true);g.maintenancePaidThisRound=paid;if(paid+1e-6<maintenance)g.fiscalCrisis=true}
export function taxPerPerson(game:GameEngine,personalNetIncome:number,totalNetIncome=personalNetIncome){const c=game.cfg.government;const fixed=c.taxFixed*game.state.priceIndex;const income=Math.max(0,personalNetIncome)*c.taxIncomeRate;const debtServiceNeed=game.state.debt*c.taxDebtServiceRate;const debtShare=totalNetIncome>0?debtServiceNeed*(Math.max(0,personalNetIncome)/totalNetIncome):0;return fixed+income+debtShare}
export function convertGovernmentResources(game:GameEngine){const g=game.state.government;let proceeds=0,basis=0,failed=0;const lots=[...g.investmentLots];g.investmentLots=[];for(const lot of lots){const failure=game.random()<game.cfg.investmentFailureRate[lot.grade];basis+=lot.costBasis;if(failure){failed++;continue}const rate=Math.max(0,game.resourceInterest(lot.type,lot.grade)+game.state.eventInterestDelta);proceeds+=lot.units*game.marketPrice(lot.grade,lot.type)*(1+rate)*game.state.economicIncomeFactor}g.resourceHoldings={low:0,mid:0,high:0};g.resourceCostBasis={low:0,mid:0,high:0};g.nonRenewableHoldings={low:0,mid:0,high:0};g.nonRenewableCostBasis={low:0,mid:0,high:0};g.budget+=proceeds;g.realizedInvestmentProfit=proceeds-basis;if(proceeds||failed)record(game,'resource_conversion',0,`Quy đổi lao động Nhà nước +${proceeds.toFixed(2)}; ${failed} lô thất bại; P/L ${g.realizedInvestmentProfit.toFixed(2)}`)}
export function recoverScarceResourcesBeforeSubsidy(game:GameEngine){if(game.state.government.fiscalCrisis)return;let envelope=spendable(game)*game.cfg.government.recoverySpendingShare;const grades=(["low","mid","high"] as const).map(grade=>({grade,ratio:game.state.pool[grade]/game.cfg.resource[grade].carryingCapacity})).sort((a,b)=>a.ratio-b.ratio);for(const {grade,ratio} of grades){if(ratio>=game.cfg.government.recoveryTriggerPoolRatio)continue;const unitCost=game.marketPrice(grade,'renewable')*game.cfg.recovery.marketPriceRate*game.state.recoveryCostMultiplier;const room=Math.max(0,Math.floor(game.cfg.resource[grade].carryingCapacity-game.state.pool[grade]-game.state.pendingRecovery[grade]));const cap=Math.min(room,Math.max(1,Math.floor(game.cfg.resource[grade].initialPool*game.cfg.government.maxRecoveryInitialPoolShare)));const units=Math.min(cap,Math.floor(envelope/unitCost));if(units<=0)continue;const cost=units*unitCost;const paid=spend(game,'renewable_recovery',cost,`Ưu tiên tái tạo ${units} renewable/${grade} {amount}`);if(paid>=cost-.001){game.state.pendingRecovery[grade]+=units;envelope-=paid}}}
export function prepareGovernmentSubsidies(game:GameEngine){const g=game.state.government;g.subsidyRate={low:0,mid:0,high:0};if(spendable(game)<=0||g.fiscalCrisis)return;for(const grade of ["low","mid","high"] as const){const scarcity=Math.max(0,1-game.state.pool[grade]/game.cfg.resource[grade].carryingCapacity);const priceStress=Math.max(game.marketPrice(grade,'renewable')/game.cfg.resource[grade].basePrice/game.state.priceIndex,game.marketPrice(grade,'nonrenewable')/game.cfg.nonRenewableResource[grade].basePrice/game.state.priceIndex);if(priceStress>=game.cfg.government.subsidyTriggerPriceMultiple||scarcity>.35){const base=grade==='low'?game.cfg.government.lowSubsidyRate:grade==='mid'?game.cfg.government.midSubsidyRate:game.cfg.government.highSubsidyRate;g.subsidyRate[grade]=Math.min(base*2,base*(1+scarcity))}}if(Object.values(g.subsidyRate).some(x=>x>0))record(game,'subsidy_policy',0,`Trợ giá theo khan hiếm Hạ ${(g.subsidyRate.low*100).toFixed(1)}% / Trung ${(g.subsidyRate.mid*100).toFixed(1)}% / Thượng ${(g.subsidyRate.high*100).toFixed(1)}%`)}
function stabilizeSocialFund(game:GameEngine){if(game.state.socialSecurity.support>=0)return;const need=-game.state.socialSecurity.support;game.state.socialSecurity.support=0;game.fundSocialSupport(need,'ổn định quỹ an sinh')}
function repayDebt(game:GameEngine){const g=game.state.government;if(game.state.debt<=0||g.fiscalCrisis)return;const stress=game.state.debt>Math.max(1,g.budget)*game.cfg.government.debtStressRatio;const share=stress?game.cfg.government.debtRepaymentShare:.12;const amount=Math.min(game.state.debt,spendable(game)*share);const paid=spend(game,'debt_repayment',amount,'Trả gốc nợ công {amount}');game.state.debt-=paid;g.debtRepaidThisRound+=paid}
function investInResources(game:GameEngine){const g=game.state.government;if(g.fiscalCrisis)return;let envelope=spendable(game)*game.cfg.government.investmentSpendingShare;const candidates:Array<{type:ResourceType;grade:'mid'|'high';score:number}>=[];for(const type of ['renewable','nonrenewable'] as const)for(const grade of ['mid','high'] as const){const pool=game.resourcePool(type)[grade],cfg=game.resourceConfig(type,grade),ratio=pool/cfg.initialPool,pm=game.marketPrice(grade,type)/(cfg.basePrice*game.state.priceIndex);if(ratio>=game.cfg.government.investmentMinPoolRatio&&pm<=game.cfg.government.investmentMaxPriceMultiple)candidates.push({type,grade,score:(1-game.cfg.investmentFailureRate[grade])*(1+cfg.interest)-1})}candidates.sort((a,b)=>b.score-a.score);for(const x of candidates){const pool=game.resourcePool(x.type),price=game.marketPrice(x.grade,x.type);const units=Math.min(Math.floor(pool[x.grade]*game.cfg.government.legalMaxResourcePurchasePoolShare),Math.floor(pool[x.grade]*game.cfg.government.strategyMaxResourcePurchasePoolShare),Math.floor(envelope/price));if(units<=0)continue;const cost=units*price,paid=spend(game,'resource_investment',cost,`Nhà nước mua phương tiện lao động ${units} ${x.type}/${x.grade} {amount}`);if(paid<cost-.001)continue;pool[x.grade]-=units;g.investmentLots.push({type:x.type,grade:x.grade,units,costBasis:cost,purchaseRound:game.state.round,buyerCharacterId:null,purchaseAgeStage:null});(x.type==='renewable'?g.resourceHoldings:g.nonRenewableHoldings)[x.grade]+=units;envelope-=paid}}
export function runGovernmentTurn(game:GameEngine){const g=game.state.government;if(g.actedThisRound)return;stabilizeSocialFund(game);repayDebt(game);investInResources(game);g.actedThisRound=true;if(g.interventions.length===0)record(game,'none',0,'Không can thiệp thêm')}
export function quoteResourceSubsidy(game:GameEngine,grade:ResourceGrade,grossCost:number){
  const g=game.state.government,rate=g.subsidyRate[grade];
  if(rate<=0||g.fiscalCrisis)return 0;
  return Math.min(grossCost*rate,spendable(game));
}
export function applyResourceSubsidy(game:GameEngine,grade:ResourceGrade,type:ResourceType,grossCost:number){const g=game.state.government,rate=g.subsidyRate[grade];if(rate<=0||g.fiscalCrisis)return 0;const paid=spend(game,'price_subsidy',Math.min(grossCost*rate,spendable(game)),`Trợ giá ${type}/${grade} {amount}`);g.subsidySpentThisRound+=paid;return paid}
export function accruePublicDebt(_game:GameEngine){}
